# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

In [2]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr1.ndim

1

In [7]:
arr2=arr1.reshape(2,5)

In [8]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
arr2.ndim

2

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

## Question:7

### Create 5x5 an array and find the square of an array?

## Question:8

### Create 5x6 an array and find the mean?

## Question:9

### Find the standard deviation of the previous array in Q8?

## Question:10

### Find the median of the previous array in Q8?

## Question:11

### Find the transpose of the previous array in Q8?

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

## Question:13

### Find the determinant of the previous array in Q12?

## Question:14

### Find the 5th and 95th percentile of an array?

## Question:15

### How to find if a given array has any null values?