# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

In [2]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr1.ndim

1

In [7]:
arr2=arr1.reshape(2,5)

In [8]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
arr2.ndim

2

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
import numpy as np
a=np.arange(10).reshape(2,5)
b=np.ones((2,5))

In [4]:
np.vstack((a,b))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [5]:
np.hstack((a,b))

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [6]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [8]:
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [15]:
arr=np.arange(15).reshape(5,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [43]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
arr**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

In [45]:
np.square(arr)

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

## Question:8

### Create 5x6 an array and find the mean?

In [19]:
arr=np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [21]:
arr.mean()

15.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [22]:
arr.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [23]:
np.median(arr)

15.5

## Question:11

### Find the transpose of the previous array in Q8?

In [24]:
arr.T

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

In [25]:
arr.T.shape

(6, 5)

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [26]:
arr1=np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
np.trace(arr1)

34

In [30]:
arr1.diagonal().sum()

34

## Question:13

### Find the determinant of the previous array in Q12?

In [36]:
from numpy.linalg import det
det(arr1)

-1.820448242817726e-31

## Question:14

### Find the 5th and 95th percentile of an array?

## Question:15

### How to find if a given array has any null values?

In [46]:
arr=np.arange(1,15)

In [48]:
(arr==None).any()

False

In [49]:
arr2=np.array([1,2,4,None,5,7])

In [50]:
arr2

array([1, 2, 4, None, 5, 7], dtype=object)

In [51]:
(arr2==None).any()

True