# Assignment 1

Name : Sajid Munawar

R NO : PIAIC142475

Assig: 100 methods of Numpy

In [1]:
!conda install numpy

Solving environment: ...working... done

# All requested packages already installed.



In [3]:
numpy.__version__

NameError: name 'numpy' is not defined

In [4]:
import numpy as np

In [9]:
np.__version__

'1.18.1'

In [8]:
!pip install --upgrade numpy

Requirement already up-to-date: numpy in c:\users\sajid\anaconda3\lib\site-packages (1.19.4)


In [1]:
import numpy as np

In [2]:
np.__version__    #The version has been updated

'1.19.2'

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [4]:
type(x)

numpy.ndarray

## 1 : Create one dimensional array

In [189]:
a=[x for x in range(1,11)]             #1
type(a)

list

In [6]:
arr=np.array(a)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2 : Create two dimensional array

In [11]:
a=[[1,2,3],[4,5,6],[7,8,9]]           #2
arr1=np.array(a)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [261]:
a=np.arange(16).reshape(4,4)
a.ndim

2

In [291]:
# creating two dimensional list using for loop
import numpy as np
matrix=[]
for i in range(3):
    for j in range(3):
        num=np.random.randint(0,100,1)
        matrix.append(j+num)
#     matrix.append(a)
arr=np.array(matrix)
arr1=arr.reshape(3,-1)
print("Dimension of arr1 =", arr1.ndim)
arr1

Dimension of arr1 = 2


array([[58, 72,  2],
       [ 5,  8, 33],
       [ 2, 46, 54]])

## 3 : find dimensisons of array  

In [15]:
            #3
print("Dimension of first array",arr.ndim),
print("Dimension of Second array",arr1.ndim)
# arr1.ndim

Dimension of first array 1
Dimension of Second array 2


## 4 : shape of array

In [16]:
# Shpae of array                       #4
print("Shape of first array",arr.shape),
print("Shape of Second array",arr1.shape)

Shape of first array (10,)
Shape of Second array (3, 3)


## 5 : zeros

In [23]:
# Zeros                                #5
arr=np.zeros(5)    #one dimension zeros
print("arr= \n",arr)
arr1=np.zeros((3,4))  #two dimension zeros
print("arr1= \n",arr1)

arr= 
 [0. 0. 0. 0. 0.]
arr1= 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 6 : ones

In [263]:
# Ones                                #6
arr=np.ones(5)    #one dimension ones
print("arr= \n",arr)
arr1=np.ones((3,4))  #two dimension ones
print("arr1= \n",arr1)

arr= 
 [1. 1. 1. 1. 1.]
arr1= 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 7 : eye function

In [27]:
#Eye function                                          7
# It make diagonal elements 1 and rest 0
arr =np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
arr=np.eye(5,7)    # it start from left
arr

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

## 8 : diag method

In [269]:
# Diagonal function with provided list      8
arr=np.diag([1,3,5,7,9])
arr

array([[1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 9]])

In [34]:
np.diag(arr)

array([1, 3, 5, 7, 9])

In [270]:
np.diag(arr).sum()    #these both methods do the same job

25

In [271]:
np.trace(arr)

25

## 9 : randint

In [286]:
# randint                                     9
import numpy as np
# arr=np.random.randint(min, max, total_values)      syntax
arr=np.random.randint   (1, 100,     4)
print(arr)
np.random.randint(10)   #it will create a random number between given range

[46 99 88 98]


3

## 10 : rand

In [17]:
# np.random.rand generates a random value between 0 to 1
arr=np.random.rand()
arr

0.8114068356951671

In [18]:
# if we need multiple values we will write total number of values in parenthes
arr=np.random.rand(3)
arr

array([0.73184022, 0.35999153, 0.73382108])

In [24]:
# if we need multiple values we will write total number of values in parenthes
arr=np.random.rand(3)
arr*10//1

array([1., 9., 4.])

In [25]:
# we can also create two dimensional array using rand 
arr=np.random.rand(2,3)
arr

array([[0.45407924, 0.52424382, 0.55742047],
       [0.22708646, 0.53774366, 0.89792128]])

## 11 : randn

In [27]:
# using randn we can create a random number close to zero
# it also generate - number
arr=np.random.randn(3)
arr

array([ 0.47102875, -0.16890489,  1.06091424])

In [289]:
arr=np.random.randn()

In [290]:
arr

0.3687257990906142

## 12 : array indexing

In [21]:
# indexing starts from 0 and ends at length -1
#         0  1   2   3   4
# arr= [  1, 2,  3,  4,  5]
#        -5 -4  -3  -2  -1
arr=np.array([1,2,3,4,5,6,7,8,9])
print("index 2 = ",arr[2],"& index 5 =",arr[5])

index 2 =  3 & index 5 = 6


## 13 : array slicing

In [31]:
#  array_name[start:end,step]
# slicing always move from left to right
li=list(range(0,10))
arr=np.array(li)
arr
arr1=arr[2:5]
arr1


array([2, 3, 4])

In [32]:
arr2=arr[-5:-2]
arr2

array([5, 6, 7])

In [33]:
arr3=arr[4:]
arr3

array([4, 5, 6, 7, 8, 9])

In [34]:
arr4=arr[:4]
arr4

array([0, 1, 2, 3])

In [35]:
arr5=arr[-1:-5:-1]
arr5

array([9, 8, 7, 6])

In [2]:
import numpy as np

In [6]:
x=np.ones((5,5))

In [7]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
x[1:-1,1:-1]=0

In [9]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
x[1:-1,1:-1]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [192]:
x=np.ones((5,5))

In [193]:
x[::2]=0
x

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [194]:
x[:,::2]=0
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [200]:
x=np.ones((5,5))

In [201]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [204]:
x[::2,::2]=0

In [205]:
x

array([[0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.]])

In [53]:
x=np.arange(0,50).reshape(10,5)

In [54]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [55]:
x[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [6]:
# 3d array slicing
import numpy as np
arr=np.arange(1,65).reshape(4,4,4)

In [7]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60],
        [61, 62, 63, 64]]])

In [15]:
a=arr[2][2][2]
a

43

In [16]:
type(a)

numpy.int64

In [5]:
arr[1,1:,1:]

array([[22, 23, 24],
       [26, 27, 28],
       [30, 31, 32]])

##  14 : Reshape

In [37]:
arr=np.random.randint(1,100,12)
arr

array([97, 86, 91, 49, 85, 83, 12,  3, 43, 78, 63, 84])

In [43]:
arr=arr.reshape(3,4)
arr

array([[49, 35, 18, 69],
       [ 3, 99, 19, 61],
       [90, 20,  5, 71]])

In [44]:
# arr=np.random.randint(1,100,12)
arr = arr.reshape(2,6)
arr

array([[49, 35, 18, 69,  3, 99],
       [19, 61, 90, 20,  5, 71]])

In [45]:
arr=arr.reshape(4,3)
arr

array([[49, 35, 18],
       [69,  3, 99],
       [19, 61, 90],
       [20,  5, 71]])

In [47]:
arr=arr.reshape(12)
arr

array([49, 35, 18, 69,  3, 99, 19, 61, 90, 20,  5, 71])

In [52]:
arr=np.random.randint(1,100,11)
arr=arr.reshape(6,2)
arr         # it will give error

ValueError: cannot reshape array of size 11 into shape (6,2)

In [43]:
# creating two dimensional list using for loop
import numpy as np
matrix=[]
for i in range(3):
    a=[]
    for j in range(3):
        num=np.random.randint(0,100,1)
        a.append(j+num)
    matrix.append(a)
arr=np.array(matrix)
print("Dimension of arr1 =", arr.ndim)
arr

Dimension of arr1 = 3


array([[[41],
        [36],
        [66]],

       [[95],
        [70],
        [96]],

       [[ 0],
        [51],
        [38]]])

In [206]:
import numpy as np
arr=np.array(list(range(1,11)))
print(arr)
arr=np.random.randint(1,100,12)
arr

[ 1  2  3  4  5  6  7  8  9 10]


array([19, 63, 36, 60, 86, 67, 71,  5, 75, 62, 60, 22])

In [3]:
arr=arr.reshape(6,-1)
arr

array([[94, 61],
       [16, 62],
       [46, 72],
       [82, 10],
       [64, 86],
       [52, 16]])

In [4]:
arr=arr.reshape(3,-1)
arr

array([[94, 61, 16, 62],
       [46, 72, 82, 10],
       [64, 86, 52, 16]])

In [6]:
arr=arr.reshape(4,-1)
arr

array([[94, 61, 16],
       [62, 46, 72],
       [82, 10, 64],
       [86, 52, 16]])

In [8]:
arr=arr.reshape(12,-1)
arr

array([[94],
       [61],
       [16],
       [62],
       [46],
       [72],
       [82],
       [10],
       [64],
       [86],
       [52],
       [16]])

## 15 : Seed

In [24]:
import numpy as np
# seed function should have a value
# seed function fix the random numbers 
np.random.seed(0)
arr=np.random.randint(1,100,12)
arr

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89])

In [34]:
print(type(arr))
print(arr.shape)

<class 'numpy.ndarray'>
(3, 3, 1)


In [46]:
# indexing
arr1[1,1]

14

In [47]:
arr1[1][0]

79

## 16 : 2 dimensional array slicing

In [ ]:
# 2 dimensional array slicing

In [54]:
arr1[1:,2:]

array([[87],
       [71]])

In [57]:
np.random.seed(1)
arr=np.random.randint(1,500,30).reshape(6,5)
arr

array([[ 38, 236, 397,  73, 256],
       [394, 204, 134, 336, 449],
       [145, 130, 461,  72, 238],
       [391, 282, 179, 277, 255],
       [358, 403, 469, 396, 253],
       [491, 157, 414, 399,  51]])

In [58]:
arr[2:-1,:3]

array([[145, 130, 461],
       [391, 282, 179],
       [358, 403, 469]])

In [61]:
arr[2:,-2:]

array([[ 72, 238],
       [277, 255],
       [396, 253],
       [399,  51]])

## 17 : arange

In [1]:
import numpy as np

In [292]:
arr=np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [293]:
arr>10


array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [294]:
b=arr[arr>10]
b

array([11, 12, 13, 14, 15])

In [295]:
b.size

5

## 18 : conditional selection

In [6]:
# Conditional selectioin
b=arr[arr>10]
b

array([11, 12, 13, 14, 15])

In [10]:
arr[arr%2==0]=0
arr

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15])

In [11]:
arr[2:-4]

array([ 3,  0,  5,  0,  7,  0,  9,  0, 11])

## 19 : sum method

In [3]:
arr=np.random.randint(1,1000,50)
arr

array([851, 203, 330, 149, 636,  47, 771, 377, 259, 282, 846, 533, 362,
       836, 684, 923, 545, 954, 563, 200, 794, 252, 325,  12, 306, 241,
       498,  14, 548, 938, 619, 225, 399, 438, 902, 384, 278,  55, 687,
       134, 947, 499, 449, 991, 278, 848, 313, 200, 634, 317])

In [10]:
arr[arr>300].sum()

21047

In [215]:
a=np.random.randint(1,50,10)
a

array([33, 46,  2, 21, 38,  1, 44, 17, 16, 10])

In [216]:
a.sum()

228

## 20 : size 

In [14]:
arr[arr>180].size

44

In [35]:
import numpy as np
li=range(1,101)
# arr=np.array(li)
arr=np.array(li).size
print(arr)
arr1=np.arange(1,501).size
arr1

100


500

##  21 : itemsize

In [296]:
# the size in bytes of each element of the array.
arr=np.arange(1,51)
arr.itemsize

8

In [299]:
# the size in bytes of each element of the array.
arr=np.arange(1,51,dtype="int32")
arr.itemsize

4

In [300]:
# the size in bytes of each element of the array.
arr=np.arange(1,51,dtype="float32")
arr.itemsize

4

In [301]:
# the size in bytes of each element of the array.
arr=np.arange(1,51,dtype="int64")
arr.itemsize

8

In [302]:
# the size in bytes of each element of the array.
arr=np.arange(1,51,dtype="float64")
arr.itemsize

8

In [303]:
# the size in bytes of each element of the array.
arr=np.arange(1,51,dtype="int16")
arr.itemsize

2

In [304]:
# the size in bytes of each element of the array.
arr=np.arange(1,51,dtype="int8")
arr.itemsize

1

## 22: ndarray.type and dtype

In [44]:
arr=np.arange(1,11)
print(type(arr))
arr.dtype


<class 'numpy.ndarray'>


dtype('int64')

In [46]:
# The type of the array can also be explicitly specified at creation time:

c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [305]:
type(c)

numpy.ndarray

In [308]:
c.dtype

dtype('int64')

In [312]:
np.dtype??

## 23 : np.empty

In [63]:
arr=np.empty(1)
arr1=np.empty(4)
arr2=np.empty((2,4))
arr3=np.empty((2,0))   ## if any value is 0 it will create an empty array
arr4=np.empty((0,2))
print("arr = " ,arr, "shape = " , arr.shape)
print("arr1 = ",arr1,"shape = ", arr1.shape)
print("arr2 = ",arr2,"shape = ", arr2.shape)
print("arr3 = ",arr3,"shape = ", arr3.shape)
print("arr4 = ",arr4,"shape = ", arr4.shape)
print(arr.dtype)

arr =  [6.91817212e-310] shape =  (1,)
arr1 =  [1. 2. 3. 4.] shape =  (4,)
arr2 =  [[4.67299121e-310 0.00000000e+000 1.78488218e+161 2.51715952e+180]
 [1.40022644e+195 1.05774260e-153 1.12044105e+219 6.91817212e-310]] shape =  (2, 4)
arr3 =  [] shape =  (2, 0)
arr4 =  [] shape =  (0, 2)
float64


In [314]:
arr2=np.empty((2,4))
arr2

array([[4.65901867e-310, 0.00000000e+000, 1.00814451e+261,
        2.02763010e+174],
       [2.46635954e-154, 9.82202796e+252, 6.13357570e-095,
        4.82406545e+228]])

## 24 : np.linespace 

In [315]:
#Return evenly spaced numbers over a specified interval
arr=np.arange(10,30,5)
np.linspace(1,50,12)
# print(arr)
# arr=np.arange(0,3,0.3)
# print(arr) 

array([ 1.        ,  5.45454545,  9.90909091, 14.36363636, 18.81818182,
       23.27272727, 27.72727273, 32.18181818, 36.63636364, 41.09090909,
       45.54545455, 50.        ])

In [246]:
a=np.arange(1,50,5)
a

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [232]:
b=np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [233]:
b[3]

4

In [80]:
# generally due to float precesion it is not predicted number of elements so
# it is usually better to use the function linspace that receives as an argument
# the number of elements that we want, instead of the step:
arr=np.linspace(0,3,9)  # in the last we tell number of elements instead step
arr

array([0.   , 0.375, 0.75 , 1.125, 1.5  , 1.875, 2.25 , 2.625, 3.   ])

In [82]:
arr=np.arange(3,4)
print(arr)

[3]


## 25 : default random number generator

In [321]:
rg = np.random.default_rng(1)
rg.random((2,3))

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [86]:
a = np.floor(10*rg.random((3,4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

## 26 : resize

In [326]:
# np.resize(array,(row,col))
arr=np.array([[1,2],[3,4]])
print(arr.shape)
print(type(arr))

(2, 2)
<class 'numpy.ndarray'>


In [328]:
np.resize(arr,(2,3))

array([[1, 2, 3],
       [4, 1, 2]])

In [329]:
np.resize(arr,(5,2))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2]])

In [327]:
np.resize(arr,(2,5))

array([[1, 2, 3, 4, 1],
       [2, 3, 4, 1, 2]])

In [108]:
np.resize(arr,(1,3))

array([[1, 2, 3]])

In [109]:
np.resize(arr,(3,2))

array([[1, 2],
       [3, 4],
       [1, 2]])

In [110]:
np.resize(arr,(3,1))

array([[1],
       [2],
       [3]])

In [333]:
arr

array([[1, 2],
       [3, 4]])

In [332]:
arr.resize((2,5))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

## Note:

np.reshape does not effect or change 
the original array but np.resize perform in-place reshaping of the array

In [427]:
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [428]:
arr1=arr.reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [429]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [435]:
np.resize(arr,(5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
arr.resize(2,10)

In [36]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

## 27 : np.ravel

In [341]:
# It is equivalent to reshape(-1, order=order).
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [346]:
np.ravel(x).shape

(6,)

In [342]:
x.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [343]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [344]:
np.resize(x,(-1))

array([1, 2, 3, 4, 5])

## 28 : astype

In [355]:
# syntax
# array_name.astype(dtype)

In [361]:
x=np.array([1 , 2.5 , 3.3 , 4.6])
x

array([1. , 2.5, 3.3, 4.6])

In [365]:
x.astype(int)        ## it converts the type of the array and truncate the decimal part

array([1, 2, 3, 4])

In [366]:
x   # not modified the original array

array([1. , 2.5, 3.3, 4.6])

In [350]:
arr=np.arange(1,11,dtype=float)

In [351]:
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [354]:
import numpy as np
arr.astype(int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [359]:
x=np.random.randn(4)
print(x)
np.ceil(x)
# x.astype(dtype=int)
# x

[-1.18277283  0.20710062 -1.026403    0.10730143]


array([-1.,  1., -1.,  1.])

## 29 : arithmetic operations

In [119]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
b=arr+2
b

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [122]:
arr   # will not change the original array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
c=arr*5
c

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [126]:
d=arr**2
d

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

## 30 : np.prod

In [132]:
#  it multiplicate the elements of the array
arr=np.arange(1,5)
arr.prod()

24

In [133]:
arr=np.arange(1,11)
arr.prod()

3628800

In [146]:
# The product of an empty array is the neutral element 1:
np.prod([])

1.0

## 31 : np.floor

In [134]:
arr=np.random.randn(5)
arr

array([ 1.08215952,  0.76427971, -0.62044153,  1.09015846, -0.39725873])

In [137]:
np.floor(arr)

array([ 1.,  0., -1.,  1., -1.])

In [158]:
arr=np.linspace(1,6,12)
arr

array([1.        , 1.45454545, 1.90909091, 2.36363636, 2.81818182,
       3.27272727, 3.72727273, 4.18181818, 4.63636364, 5.09090909,
       5.54545455, 6.        ])

In [159]:
np.floor(arr)

array([1., 1., 1., 2., 2., 3., 3., 4., 4., 5., 5., 6.])

In [160]:
np.floor(np.linspace(1,5,7))

array([1., 1., 2., 3., 3., 4., 5.])

## 32 : np.ceil 

In [64]:
arr=np.random.randn(5)

In [65]:
arr

array([ 0.7355136 ,  0.72334339,  0.8518396 , -0.14066598,  0.67652077])

In [66]:
np.ceil(arr)

array([ 1.,  1.,  1., -0.,  1.])

In [67]:
arr=np.linspace(1,6,12)
arr

array([1.        , 1.45454545, 1.90909091, 2.36363636, 2.81818182,
       3.27272727, 3.72727273, 4.18181818, 4.63636364, 5.09090909,
       5.54545455, 6.        ])

In [68]:
np.ceil(arr)  #np.ceil does not change the original array

array([1., 2., 2., 3., 3., 4., 4., 5., 5., 6., 6., 6.])

In [69]:
arr

array([1.        , 1.45454545, 1.90909091, 2.36363636, 2.81818182,
       3.27272727, 3.72727273, 4.18181818, 4.63636364, 5.09090909,
       5.54545455, 6.        ])

## 33 : np.trunc

In [368]:
# Return the truncated value of the input, element-wise.
arr=np.random.randn(5)
arr

array([-0.13298173,  0.08245736, -0.83286575, -0.98885584,  1.32079066])

In [369]:
np.trunc(arr)

array([-0.,  0., -0., -0.,  1.])

In [371]:
arr   # does not modified the original array

array([-0.13298173,  0.08245736, -0.83286575, -0.98885584,  1.32079066])

## 34 : np.rint

In [148]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.rint(a)

array([-2., -2., -0.,  0.,  2.,  2.,  2.])

## 35 : np.fromfunction

In [149]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [151]:
arr=np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
arr

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [153]:
arr=np.fromfunction(lambda i, j: i - j, (3, 3), dtype=int)
arr

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

## 36 : np.geomspace 

In [372]:
np.geomspace(1,100,4)   #similar to linespace but in log scale

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [165]:
np.geomspace(1,1000,10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

##  37 : np.identity

In [167]:
arr=np.eye(5,7)
arr

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [174]:
np.identity(3 ,dtype=bool)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [175]:
np.identity(3 ,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [176]:
np.identity(3) # by default it will be float

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [375]:
np.identity((3,4))   # it does not take two values or shape it creates a square matrix

TypeError: 'tuple' object cannot be interpreted as an integer

##  38 : np.ones_like

In [184]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [193]:
b=arr.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [186]:
np.ones_like(b)

array([[1, 1, 1],
       [1, 1, 1]])

## 39 : np.zeros_like

In [188]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [191]:
b=arr.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [192]:
np.zeros_like(b)

array([[0, 0, 0],
       [0, 0, 0]])

## 40 : np.full_like

In [380]:
x = np.arange(6, dtype=int)
x

array([0, 1, 2, 3, 4, 5])

In [381]:
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1])

In [386]:
np.full_like(x, 0.2,dtype=float)

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.2])

In [196]:
np.full_like(x, 0.1, dtype=np.double)

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [197]:
np.full_like(x, np.nan, dtype=np.double)

array([nan, nan, nan, nan, nan, nan])

## 41 : np.empty_like

In [393]:
a = ([1,2,3], [4,5,6])                         # a is array-like
np.empty_like(a)

array([[4596373779694328218, 4596373779694328218, 4596373779694328218],
       [4596373779694328218, 4596373779694328218, 4596373779694328218]])

In [394]:
np.empty_like((3,2))

array([94299589531856,              0])

## 42 : np.atleast_1d 

## Note :

In [208]:
np.atleast_1d(1.0)

array([1.])

In [395]:
x = np.arange(9.0).reshape(3,3)
b=np.atleast_1d(x)
b.ndim

2

In [396]:
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [210]:
np.atleast_1d(x) is x

True

## 42 : np.atleast_2d 

In [213]:
x=np.atleast_2d(3.0)
x

array([[3.]])

In [215]:
x.ndim      ## two dimensional array

2

In [216]:
x = np.arange(3.0)
np.atleast_2d(x)

array([[0., 1., 2.]])

In [221]:
x.reshape(3,1)

array([[0.],
       [1.],
       [2.]])

In [222]:
np.atleast_2d(x).base is x

True

In [224]:
# as much elements we pas it will convert all of them into 2d array
np.atleast_2d(1, [1, 2], [[1, 2]])

[array([[1]]), array([[1, 2]]), array([[1, 2]])]

## 43 : np.atleast_3d

In [225]:
np.atleast_3d(3.0)

array([[[3.]]])

In [226]:
np.atleast_3d(3.0).ndim

3

In [227]:
x = np.arange(3.0)
np.atleast_3d(x)

array([[[0.],
        [1.],
        [2.]]])

In [228]:
x = np.arange(3.0)
np.atleast_3d(x).shape

(1, 3, 1)

In [402]:
x = np.arange(16).reshape(2,2,2,2)
print(x.ndim)
np.atleast_3d(x).ndim

4


4

In [399]:
x = np.arange(12.0).reshape(4,3)
np.atleast_3d(x).shape

(4, 3, 1)

In [231]:
np.atleast_3d(x).base is x.base

True

In [232]:
for arr in np.atleast_3d([1, 2], [[1, 2]], [[[1, 2]]]):
    print(arr, arr.shape) 

[[[1]
  [2]]] (1, 2, 1)
[[[1]
  [2]]] (1, 2, 1)
[[[1 2]]] (1, 1, 2)


## 44 : np.mat

In [405]:
arr=np.arange(27).reshape(3,9)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [408]:
matrix=np.mat(arr)
matrix

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [409]:
type(matrix)

numpy.matrix

In [234]:
x = np.array([[1, 2], [3, 4]])

In [235]:
m = np.asmatrix(x)

In [236]:
x[0,0] = 5
m

matrix([[5, 2],
        [3, 4]])

## 45 : np.astype 

In [123]:

x = np.array([1, 2, 2.5])
x

array([1. , 2. , 2.5])

In [124]:
x.astype(bool)

array([ True,  True,  True])

In [125]:
x.astype(float)

array([1. , 2. , 2.5])

In [128]:
dd=x.astype(int)

In [129]:
dd

array([1, 2, 2])

In [130]:
x

array([1. , 2. , 2.5])

## 46 : np.squeeze

In [241]:
x = np.array([[[0], [1], [2]]])
x.shape

(1, 3, 1)

In [246]:
np.squeeze(x).shape

(3,)

In [247]:
np.squeeze(x, axis=0).shape

(3, 1)

In [248]:
x = np.array([[1234]])
x.shape

(1, 1)

In [249]:
x.squeeze()

array(1234)

In [250]:
np.squeeze(x)[()]

1234

In [410]:
a=np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [413]:
x.squeeze().ndim

4

In [421]:
arr=np.arange(6).reshape(1,-1)

In [422]:
arr.shape

(1, 6)

In [423]:
arr

array([[0, 1, 2, 3, 4, 5]])

In [424]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [425]:
arr.shape

(6,)

## 47 : np.vstack

In [251]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [252]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

## 48 : np.vsplit

In [436]:
x=np.arange(1,17).reshape(4,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [441]:
np.vsplit(x,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [443]:
np.vsplit(x,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [446]:
np.vsplit(x,[1,3])   # we can fancy split by passing an list

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [442]:
np.array([3, 6])

array([3, 6])

In [261]:
np.vsplit(x, np.array([3, 6]))

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([], shape=(0, 4), dtype=int64)]

In [262]:
x = np.arange(8.0).reshape(2, 2, 2)
x

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [263]:
np.vsplit(x,2)

[array([[[0., 1.],
         [2., 3.]]]),
 array([[[4., 5.],
         [6., 7.]]])]

## 49 : np.transpose

In [264]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [265]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [124]:
x = np.ones((1, 2, 3))
print(x)
np.transpose(x, (1, 0, 2)).shape

[[[1. 1. 1.]
  [1. 1. 1.]]]


(2, 1, 3)

## 50 : np.swapaxes

In [125]:
np.swapaxes??

In [267]:
x = np.array([[1,2,3]])
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

In [268]:
x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [269]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

## 51 : How to create a 1D array?

Create a 1D array of numbers from 0 to 9

In [4]:
import numpy as np
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 52 : Create a 3×3 numpy array of all True’s

In [5]:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 53 : Extract all odd numbers from arr

In [28]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [2]:
li=list(range(0,10))
li

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:
# same task with list comprehension with a large code
[i for i in range(1,10) if i%2!=0]

[1, 3, 5, 7, 9]

## 54 : Replace all odd numbers in arr with -1  

In [51]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr[arr%2!=0]=-1

In [54]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 55 :  Replace all odd numbers in arr with -1 without changing arr

In [77]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
b=arr[:].copy()
b[b%2==1]=-1
print(b)
arr

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 56 : np.sqrt

In [59]:
x=np.array((1,3,4,5,7,6))
x

array([1, 3, 4, 5, 7, 6])

In [60]:
np.sqrt(x)

array([1.        , 1.73205081, 2.        , 2.23606798, 2.64575131,
       2.44948974])

In [62]:
x   # does not change original array

array([1, 3, 4, 5, 7, 6])

## 57 : np.power

In [63]:
# syntax
# np.power(array,power)
np.power(x,3)

array([  1,  27,  64, 125, 343, 216])

In [64]:
x=np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [65]:
np.power(x,4)

array([  1,  16,  81, 256, 625])

## 58 : np.where

In [447]:
# syntax
# np.where(condition,True,False)
# it is like turnary operator
# if the condition is true it execute True(second)
# if the conditon is false it execute Fasle(third)

In [448]:
x=np.random.randint(1,101,20)

In [449]:
x

array([94, 71, 35, 38, 37, 10, 89, 87, 49, 76, 66, 50, 25, 99, 67, 30, 85,
       68, 95, 19])

In [74]:
np.where(x<50,x+50,x)

array([ 97,  70,  82,  89,  99,  80,  70,  86,  87,  51, 100,  92,  74,
        90,  87,  97,  98,  89,  52,  57])

In [76]:
x ## does not chamge original array

array([ 47,  20,  32,  39,  49,  30,  20,  86,  37,  51, 100,  42,  74,
        90,  87,  47,  48,  39,  52,   7])

In [77]:
np.where(x<50,0,x)

array([  0,   0,   0,   0,   0,   0,   0,  86,   0,  51, 100,   0,  74,
        90,  87,   0,   0,   0,  52,   0])

In [78]:
x.size

20

In [79]:
x

array([ 47,  20,  32,  39,  49,  30,  20,  86,  37,  51, 100,  42,  74,
        90,  87,  47,  48,  39,  52,   7])

In [80]:
x[x<50].size

13

In [81]:
x[x>50].size

7

In [83]:
b=x[x>50]

In [84]:
b

array([ 86,  51, 100,  74,  90,  87,  52])

In [85]:
x[0]=0

In [86]:
x

array([  0,  20,  32,  39,  49,  30,  20,  86,  37,  51, 100,  42,  74,
        90,  87,  47,  48,  39,  52,   7])

In [87]:
b

array([ 86,  51, 100,  74,  90,  87,  52])

In [90]:
x[:]=0

In [91]:
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [92]:
b

array([ 86,  51, 100,  74,  90,  87,  52])

In [450]:
arr=np.random.randn(5)
arr

array([-0.83439359, -0.75094898, -1.18020967, -0.5055592 ,  0.57270103])

In [451]:
np.where(arr<0,1,arr)

array([1.        , 1.        , 1.        , 1.        , 0.57270103])

## 59 : np.sort 

In [92]:
x=np.random.randint(1,100,20)
x

array([47, 72, 77, 15, 85,  2, 71, 43, 63, 87,  4, 23, 46, 89,  8, 66, 16,
       73,  6, 22])

In [93]:
x.sort()    # sort will modify original array

In [94]:
x

array([ 2,  4,  6,  8, 15, 16, 22, 23, 43, 46, 47, 63, 66, 71, 72, 73, 77,
       85, 87, 89])

In [95]:
b=x[x>20]
b

array([22, 23, 43, 46, 47, 63, 66, 71, 72, 73, 77, 85, 87, 89])

In [96]:
b.size

14

In [97]:
x.size

20

In [98]:
x[x>50]

array([63, 66, 71, 72, 73, 77, 85, 87, 89])

In [99]:
x>50

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [100]:
x

array([ 2,  4,  6,  8, 15, 16, 22, 23, 43, 46, 47, 63, 66, 71, 72, 73, 77,
       85, 87, 89])

In [101]:
x.size

20

##  60 : mean 

In [102]:
# mean means avarage

In [103]:
x

array([ 2,  4,  6,  8, 15, 16, 22, 23, 43, 46, 47, 63, 66, 71, 72, 73, 77,
       85, 87, 89])

In [104]:
x.mean()

45.75

## 61 : sum

In [105]:
x

array([ 2,  4,  6,  8, 15, 16, 22, 23, 43, 46, 47, 63, 66, 71, 72, 73, 77,
       85, 87, 89])

In [106]:
x.sum()

915

In [107]:
# sum of all number

## 62 : cusum

In [108]:
x

array([ 2,  4,  6,  8, 15, 16, 22, 23, 43, 46, 47, 63, 66, 71, 72, 73, 77,
       85, 87, 89])

In [109]:
x.cumsum()

array([  2,   6,  12,  20,  35,  51,  73,  96, 139, 185, 232, 295, 361,
       432, 504, 577, 654, 739, 826, 915])

In [12]:
arr=np.arange(5*6).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [13]:
np.cumsum(arr)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325,
       351, 378, 406, 435])

In [14]:
arr.cumsum(axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  8, 10, 12, 14, 16],
       [18, 21, 24, 27, 30, 33],
       [36, 40, 44, 48, 52, 56],
       [60, 65, 70, 75, 80, 85]])

In [15]:
arr.cumprod(axis=1)

array([[        0,         0,         0,         0,         0,         0],
       [        6,        42,       336,      3024,     30240,    332640],
       [       12,       156,      2184,     32760,    524160,   8910720],
       [       18,       342,      6840,    143640,   3160080,  72681840],
       [       24,       600,     15600,    421200,  11793600, 342014400]])

##  63 : cumprod

In [110]:
x

array([ 2,  4,  6,  8, 15, 16, 22, 23, 43, 46, 47, 63, 66, 71, 72, 73, 77,
       85, 87, 89])

In [111]:
x.cumprod()

array([                   2,                    8,                   48,
                        384,                 5760,                92160,
                    2027520,             46632960,           2005217280,
                92239994880,        4335279759360,      273122624839680,
          18026093239418880,  1279852619998740480,   -84331728638443520,
       -6156216190606376960,  5586699239757316096, -4745910537076473856,
       -7065847104043089920, -1671093753710247936])

In [116]:
d=np.empty((4,5))
d

array([[4.63742417e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.92110147e-310],
       [5.30276956e+180, 1.57076922e-076, 4.57046137e-071,
        4.46234818e-086, 3.35758757e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 6.45490014e+170],
       [9.77235199e+165, 9.12442024e+169, 4.00086933e+175,
        5.73635214e-143, 1.50008929e+248]])

In [117]:
b=np.empty((2,3))

In [118]:
b

array([[1., 0., 0.],
       [0., 1., 0.]])

In [119]:
d

array([[4.63742417e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.92110147e-310],
       [5.30276956e+180, 1.57076922e-076, 4.57046137e-071,
        4.46234818e-086, 3.35758757e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 6.45490014e+170],
       [9.77235199e+165, 9.12442024e+169, 4.00086933e+175,
        5.73635214e-143, 1.50008929e+248]])

In [121]:
arr1.astype(d)

NameError: name 'arr1' is not defined

In [20]:
x=np.arange(0,6).reshape(3,2)

In [21]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
np.empty_like(x)

array([[93862510159536,              0],
       [             0,              0],
       [             0,              0]])

In [30]:
np.full((2,3),False,dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [452]:
np.eye(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [34]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [453]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
np.identity(3,dtype=bool)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [42]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [43]:
np.identity(3,dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.identity(5,dtype=bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

##  fancy indexing

In [140]:
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [141]:
x[3] # we can get one number by giving an index

4

In [142]:
# what if we need more than one value??
x[3,4]  # this will give indexError 

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [144]:
# so to get more than one vlaues we often use fancy indexing 
# in this method we provide indexes with an extra square bracket
# with coma seperated index values
x[[3,7]]

array([4, 8])

In [145]:
# so fancy indexing is used to get multiple items without slicing

In [149]:
arr=np.random.randn(4)
arr

array([0.01133392, 0.50509484, 2.05973671, 0.5716682 ])

In [150]:
arr[arr<0.5]=0
arr

array([0.        , 0.50509484, 2.05973671, 0.5716682 ])

In [457]:
arr

array([-0.83439359, -0.75094898, -1.18020967, -0.5055592 ,  0.57270103])

In [459]:
np.delete(arr,[0,-1])

array([-0.75094898, -1.18020967, -0.5055592 ])

In [159]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [160]:
arr.ndim

2

In [161]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [162]:
arr[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [461]:
np.delete(arr,[0])

array([-0.75094898, -1.18020967, -0.5055592 ,  0.57270103])

## file input output

In [164]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
np.save("abc",arr)

In [167]:
np.load("abc.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
arr2=arr*2
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [177]:
np.savez("z",arr=arr,arr2=arr2)

In [178]:
npz=np.load("z.npz")

In [179]:
npz["arr"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
npz["arr2"]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
import numpy as np

## asarray again 

In [10]:
!github .

/bin/bash: github: command not found


asarray do not create a new array it just refer to an arraya

In [3]:
x=np.array(range(10))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b=np.asarray(x)

In [5]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x[0]=55

In [7]:
x

array([55,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [9]:
b

array([55,  1,  2,  3,  4,  5,  6,  7,  8,  9])

## np.flatten 

In [16]:
arr=np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
arr1=arr.flatten()
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
arr1[0]=99
arr1

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 3d array slicing again

In [1]:
import numpy as np

In [2]:
arr=np.arange(64).reshape(4,4,4)

In [3]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [12]:
arr[3,[1,3],1:-1]

array([[53, 54],
       [61, 62]])

In [13]:
arr[[1,3],1:3,1:-1]

array([[[21, 22],
        [25, 26]],

       [[53, 54],
        [57, 58]]])

In [15]:
arr[3,:,[0,-1]]

array([[48, 52, 56, 60],
       [51, 55, 59, 63]])

##  Combining array

In [16]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
b=np.arange(10,20).reshape(2,5)
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# vstack
# in vstack it is necessory that the number of column should be equal

In [ ]:
# axis 0 is equal to vstack

In [21]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
np.concatenate((a,b), axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
np.hstack((a,b))  ## because num of r and cols are equal so we can hstack here

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [ ]:
# hstack
# in hstack it is necessary that the number of rows should be equal

In [ ]:
# axis 1 is equal to hstack

In [22]:
c=np.arange(10).reshape(5,2)
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
d=np.arange(10,20).reshape(5,2)
d

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [26]:
np.hstack((c,d))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13],
       [ 4,  5, 14, 15],
       [ 6,  7, 16, 17],
       [ 8,  9, 18, 19]])

In [30]:
np.concatenate((c,d),axis=1)

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13],
       [ 4,  5, 14, 15],
       [ 6,  7, 16, 17],
       [ 8,  9, 18, 19]])

## dstack 

In [31]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
arr2=np.arange(10,19).reshape(3,3)
print(arr1)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [33]:
np.dstack((arr1,arr2))

array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17],
        [ 8, 18]]])

## split again

In [38]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
np.split(arr,[2,1])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([], shape=(0, 4), dtype=int64),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

In [40]:
np.vsplit(arr,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [41]:
np.hsplit(arr,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [45]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
np.hsplit(arr,[2,3])

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [48]:
arr2=np.arange(64).reshape(4,-1)

In [49]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [50]:
np.shape(arr2)

(4, 16)

In [53]:
np.hsplit(arr2,[5,11,15])

[array([[ 0,  1,  2,  3,  4],
        [16, 17, 18, 19, 20],
        [32, 33, 34, 35, 36],
        [48, 49, 50, 51, 52]]),
 array([[ 5,  6,  7,  8,  9, 10],
        [21, 22, 23, 24, 25, 26],
        [37, 38, 39, 40, 41, 42],
        [53, 54, 55, 56, 57, 58]]),
 array([[11, 12, 13, 14],
        [27, 28, 29, 30],
        [43, 44, 45, 46],
        [59, 60, 61, 62]]),
 array([[15],
        [31],
        [47],
        [63]])]

In [55]:
arr3=arr2.reshape(-1,4)

In [56]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63]])

In [57]:
np.vsplit(arr3,[4,10,-2])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]),
 array([[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55]]),
 array([[56, 57, 58, 59],
        [60, 61, 62, 63]])]

In [58]:
# so far i have learned stacking and spliting.

## Boolean indexing

In [59]:
names=["ali","ahmad","bilal","javed","ali","hamza","ahmad"]
names_arr=np.array(names)

In [61]:
names_arr

array(['ali', 'ahmad', 'bilal', 'javed', 'ali', 'hamza', 'ahmad'],
      dtype='<U5')

In [67]:
names_arr.size

7

In [69]:
arr=np.arange(28).reshape(7,4)

In [84]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [86]:
mask=names_arr=="ali"
mask

array([ True, False, False, False,  True, False, False])

In [91]:
mask2=names_arr!="ali"
mask2

array([False,  True,  True,  True, False,  True,  True])

In [90]:
arr[mask]

array([[ 0,  1,  2,  3],
       [16, 17, 18, 19]])

In [92]:
arr[mask2]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [75]:
a=np.array([1,5,1,4,8])
a

array([1, 5, 1, 4, 8])

In [88]:
d=a[a>1]
d

array([5, 4, 8])

## fancy indexing again

In [102]:
arr=np.arange(32).reshape(4,8)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [108]:
arr[:,[3,-1]]

array([[ 3,  7],
       [11, 15],
       [19, 23],
       [27, 31]])

In [96]:
arr[[3,0]]

array([[24, 25, 26, 27, 28, 29, 30, 31],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [1]:
import numpy as np
arr=np.arange(32).reshape(4,2,4)

In [2]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

## to get specific columns from diffrent depths of 3d array

In [24]:
# syntax
# array[[depths]][depths,[rows],[column]]
arr[[1,-1]][:,[-1,-2],[0]]

array([[12,  8],
       [28, 24]])

## to get specific rows from diffrent depths of 3d array

In [5]:
# but what if we need first row of second depth and second row of last depth??
# well lets try
arr[[1,-1],[0,1]]   #wow i got it 

array([[ 8,  9, 10, 11],
       [28, 29, 30, 31]])

In [114]:
arr[1,1] # simple indexing

array([12, 13, 14, 15])

In [121]:
arr[[2],[1],[0,2]]

array([20, 22])

## transpose 

In [126]:
a=np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [128]:
a.T  # T used as a property

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [129]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [130]:
# transpose does not change the original array

In [132]:
np.transpose(a)   # through transpose function

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

## np.modf

In [136]:
a=np.random.randn(5)
a

array([-0.21320361,  1.56547323, -0.36778793,  0.18269029, -0.41151675])

In [140]:
reminder,whole_part=np.modf(a)

In [141]:
reminder

array([-0.21320361,  0.56547323, -0.36778793,  0.18269029, -0.41151675])

In [142]:
whole_part

array([-0.,  0., -0.,  0., -0.])

In [143]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [145]:
b=np.arange(6,12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [146]:
a+b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [147]:
a*b

array([[ 0,  7, 16],
       [27, 40, 55]])

In [148]:
a/b

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [153]:
b-a

array([[6, 6, 6],
       [6, 6, 6]])

In [154]:
c=a.reshape(3,2)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [156]:
b*c

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [158]:
b@c   #dot product or matrix multiplication can be found

array([[46, 67],
       [64, 94]])

##  numpy.linalg

In [ ]:
# Has a determinant of zero. This is the definition of a Singular matrix
# (one for which an inverse does not exist)

In [164]:
from numpy.linalg import inv

In [176]:
x=np.arange(3,12).reshape(3,3)
x               

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [177]:
inv(x)

array([[ 1.93011413e+15, -3.86022825e+15,  1.93011413e+15],
       [-3.86022825e+15,  7.72045650e+15, -3.86022825e+15],
       [ 1.93011413e+15, -3.86022825e+15,  1.93011413e+15]])

In [178]:
x.T.dot(x)

array([[126, 144, 162],
       [144, 165, 186],
       [162, 186, 210]])

In [186]:
np.diag(x)

array([ 3,  7, 11])

## np.trace

In [ ]:
# compute the diagonal sum of elements

In [187]:
np.trace(x)

21

In [182]:
x

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
find all the values from array data where the values from array names are not equal to will

In [27]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])


In [28]:
data=np.random.randn(7,4)
data

array([[-2.81793589, -0.13998124, -0.1222908 , -0.39484841],
       [-0.54712758, -1.85503363,  1.90955597,  0.66331728],
       [ 1.25751155,  0.37290639, -1.70194977,  0.76486604],
       [ 0.32846369,  0.35562774,  1.83428701,  1.00832356],
       [ 0.32991736, -1.58170154,  0.01876969, -0.53477046],
       [ 0.61853903,  0.16458009,  0.89310526,  0.46935518],
       [ 1.11541744, -0.23798846, -1.01897834,  1.28984314]])

In [29]:
data[names!="Will"]

array([[-2.81793589, -0.13998124, -0.1222908 , -0.39484841],
       [-0.54712758, -1.85503363,  1.90955597,  0.66331728],
       [ 0.32846369,  0.35562774,  1.83428701,  1.00832356],
       [ 0.61853903,  0.16458009,  0.89310526,  0.46935518],
       [ 1.11541744, -0.23798846, -1.01897834,  1.28984314]])

In [31]:
data[~(names=="Will")]           # ~   this is for invert or not

array([[-2.81793589, -0.13998124, -0.1222908 , -0.39484841],
       [-0.54712758, -1.85503363,  1.90955597,  0.66331728],
       [ 0.32846369,  0.35562774,  1.83428701,  1.00832356],
       [ 0.61853903,  0.16458009,  0.89310526,  0.46935518],
       [ 1.11541744, -0.23798846, -1.01897834,  1.28984314]])

In [32]:
cond=names=="Will"

In [33]:
data[~cond]        # in this way ~ can be usefull as wellS

array([[-2.81793589, -0.13998124, -0.1222908 , -0.39484841],
       [-0.54712758, -1.85503363,  1.90955597,  0.66331728],
       [ 0.32846369,  0.35562774,  1.83428701,  1.00832356],
       [ 0.61853903,  0.16458009,  0.89310526,  0.46935518],
       [ 1.11541744, -0.23798846, -1.01897834,  1.28984314]])

In [257]:
[names!="Will"]

[array([ True,  True, False,  True, False,  True,  True])]

In [258]:
arr=np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [259]:
arr[0:2,2]

array([3, 8])

### making c checker board

In [2]:
# working on                      #line one
import numpy as np
arr=np.zeros((8,8),dtype=int)
arr

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
arr[::2,::2]=1                      #line two
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [5]:
arr[1::2,1::2]=1              #line 3 
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [8]:
arr           # i have made it in three lines i have to make in just one or two lines

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [11]:
# attempts
x[0::2,0::2]=0
x

array([[ 0,  1,  0,  3,  0,  5,  0,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0, 17,  0, 19,  0, 21,  0, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [ 0, 33,  0, 35,  0, 37,  0, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [ 0, 49,  0, 51,  0, 53,  0, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [467]:
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [471]:
x=np.ones((8,8))
x

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [477]:
y=np.zeros((8,8))
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [490]:
# y=np.zeros
y[::2]=1
y

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [491]:
y[::,1::2]=0
y

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
x=np.arange(64).reshape(8,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [502]:
x[1::2,1::2]

array([[ 9, 11, 13, 15],
       [25, 27, 29, 31],
       [41, 43, 45, 47],
       [57, 59, 61, 63]])

In [497]:
x[::2,::2]

array([[ 0,  2,  4,  6],
       [16, 18, 20, 22],
       [32, 34, 36, 38],
       [48, 50, 52, 54]])

In [495]:
x[4,5]

37

In [15]:
int_array = np.arange(1,10)  #arange by default creates an int array

In [16]:
int_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
1/int_array          #it devide every element of the array with one

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [23]:
2/int_array

array([2.        , 1.        , 0.66666667, 0.5       , 0.4       ,
       0.33333333, 0.28571429, 0.25      , 0.22222222])

In [22]:
2/3

0.6666666666666666

In [25]:
int_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.exp(int_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [2]:
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [4]:
np.exp?