Q1 Import numpy as np and print the version number.

In [1]:
import numpy as np

In [10]:
np.__version__

'1.19.2'

Q. Create a 1D array of numbers from 0 to 9

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q. Create a 3×3 numpy array of all True’s

In [12]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Q. Extract all odd numbers from arr

In [12]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# there are two methods to do this 
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [14]:
arr[~(arr%2==0)]

array([1, 3, 5, 7, 9])

Q. Replace all odd numbers in arr with -1

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Q. Replace all odd numbers in arr with -1 without changing arr

In [23]:
arr=np.arange(10)
arr1=arr[:].copy()

In [24]:
arr1[arr1%2==1]=-1
arr1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q. Convert a 1D array to a 2D array with 2 rows

In [26]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Q. Stack arrays a and b vertically

In [28]:
a=np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
b=np.repeat(1,10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. How to stack two arrays horizontally?

In [31]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a

In [34]:
a = np.array([1,2,3])

In [36]:
np.hstack((np.repeat(a,3),np.tile(a,3))) # one method

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [38]:
np.r_[np.repeat(a,3),np.tile(a,3)]      # second method

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [40]:
arr = np.array([1,2,3])                 # third jugad method
np.hstack((np.vstack((arr,arr,arr)).T.flatten(),np.hstack((arr,arr,arr)).flatten()))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Q. Get the common items between a and b

In [41]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [50]:
b[np.in1d(a,b)]

array([2, 2, 4, 4])