Q1 Import numpy as np and print the version number.

In [1]:
import numpy as np

In [10]:
np.__version__

'1.19.2'

Q. Create a 1D array of numbers from 0 to 9

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q. Create a 3×3 numpy array of all True’s

In [12]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Q. Extract all odd numbers from arr

In [12]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# there are two methods to do this 
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [14]:
arr[~(arr%2==0)]

array([1, 3, 5, 7, 9])

Q. Replace all odd numbers in arr with -1

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Q. Replace all odd numbers in arr with -1 without changing arr

In [23]:
arr=np.arange(10)
arr1=arr[:].copy()

In [24]:
arr1[arr1%2==1]=-1
arr1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q. Convert a 1D array to a 2D array with 2 rows

In [26]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Q. Stack arrays a and b vertically

In [28]:
a=np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
b=np.repeat(1,10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. How to stack two arrays horizontally?

In [31]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a

In [34]:
a = np.array([1,2,3])

In [36]:
np.hstack((np.repeat(a,3),np.tile(a,3))) # one method

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [38]:
np.r_[np.repeat(a,3),np.tile(a,3)]      # second method

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [40]:
arr = np.array([1,2,3])                 # third jugad method
np.hstack((np.vstack((arr,arr,arr)).T.flatten(),np.hstack((arr,arr,arr)).flatten()))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Q. Get the common items between a and b

In [41]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [51]:
b[np.in1d(a,b)]  # but it is giving repeatedely values

array([2, 2, 4, 4])

In [52]:
np.intersect1d(a,b)

array([2, 4])

Q. From array a remove all items present in array b

In [69]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [70]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [72]:
a                    # it is just extracting not removing

array([1, 2, 3, 4, 5])

Q. Get the positions where elements of a and b match

In [73]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [75]:
np.where(a==b)        #it will return index

(array([1, 3, 5, 7]),)

In [76]:
a[0]=7

In [78]:
np.where(a==b)    # it will return all the occurrences

(array([0, 1, 3, 5, 7]),)

Q. Get all items between 5 and 10 from a.

In [79]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [88]:
a[(a>=5)&(a<=10)]                  # first method

array([ 6,  9, 10])

In [89]:
index=np.where((a>=5)&(a<=10))     #second method

In [90]:
a[index]

array([ 6,  9, 10])

Q. Convert the function maxx that works on two scalars, to work on two arrays.

In [93]:
# Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [97]:
np.maximum(a,b)

array([6, 7, 9, 8, 9, 7, 5])

Q. Swap columns 1 and 2 in the array arr

In [101]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Q. Swap rows 1 and 2 in the array arr:

In [106]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

Q. Reverse the rows of a 2D array arr.

In [111]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [112]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Q. Reverse the columns of a 2D array arr.

In [113]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [114]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [136]:
arr=np.random.randint(5,10,15).reshape(5,3)   
arr          # it will create random numbers not float but we need float

array([[9, 5, 8],
       [7, 6, 7],
       [7, 7, 5],
       [5, 9, 9],
       [6, 9, 6]])

In [137]:
arr+np.random.random((5,3))   # after creating we covert in random float

array([[9.97114955, 5.16191472, 8.67302654],
       [7.6310746 , 6.88586435, 7.74337088],
       [7.90581352, 7.22812509, 5.54964773],
       [5.18682358, 9.88091562, 9.9610119 ],
       [6.15894987, 9.25200676, 6.71173539]])

In [134]:
arr=np.linspace(5,10,15).reshape(5,3)

In [135]:
arr   # linspace create equal diffrence numbers

array([[ 5.        ,  5.35714286,  5.71428571],
       [ 6.07142857,  6.42857143,  6.78571429],
       [ 7.14285714,  7.5       ,  7.85714286],
       [ 8.21428571,  8.57142857,  8.92857143],
       [ 9.28571429,  9.64285714, 10.        ]])

In [140]:
arr=np.random.uniform(low=5,high=10,size=(5,3)) #optional/ we can assign them low and high

In [141]:
arr

array([[5.9580014 , 8.01238464, 5.79586262],
       [5.53583551, 5.5034249 , 6.20555955],
       [9.55100032, 9.81917993, 6.57149268],
       [7.34201724, 5.38656369, 9.54477382],
       [8.89405903, 5.75833499, 6.21938169]])

Q. Print or show only 3 decimal places of the numpy array rand_arr.

In [143]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.6820897 , 0.04720026, 0.32844455],
       [0.58664675, 0.28102038, 0.39465481],
       [0.07117629, 0.33050976, 0.75629133],
       [0.41104364, 0.17461648, 0.48062589],
       [0.70128675, 0.47410777, 0.98481325]])

In [144]:
np.set_printoptions(precision=3)

In [147]:
rand_arr

array([[0.682, 0.047, 0.328],
       [0.587, 0.281, 0.395],
       [0.071, 0.331, 0.756],
       [0.411, 0.175, 0.481],
       [0.701, 0.474, 0.985]])

In [149]:
np.arange(9).reshape(3,3).ndim

2

In [156]:
x=np.arange(4)
x

array([0, 1, 2, 3])

In [155]:
a=np.zeros_like(x)
a

array([0, 0, 0, 0])

In [153]:
a.dtype

dtype('int64')

In [3]:
import numpy as np
x=np.ones((1,1))
x

array([[1.]])

In [5]:
a=np.array([[2],[3]])
b=np.array([[6],[3]])
a==b

array([[False],
       [ True]])

In [7]:
list1=[1,3,4]
list2=[8,7,5]
list3=[9,6,2]
x=np.array([[list1,list2,list3],[list3,list2,list1]])
x[1][0][1]

6

Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [10]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr


array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])

In [11]:
# np.set_printoptions(precision=3)

In [12]:
rand_arr

array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])

In [13]:
np.set_printoptions(suppress=True, precision=6)

In [14]:
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements

In [2]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
np.set_printoptions(threshold=False)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

Q. Print the full numpy array a without truncating.

In [4]:
import numpy as np
arr=np.arange(15)
arr

array([ 0,  1,  2, ..., 12, 13, 14])

In [8]:
import sys
np.set_printoptions(threshold=sys.maxsize)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.set_printoptions(threshold=True)

In [16]:
arr

array([ 0,  1,  2, ..., 12, 13, 14])

In [17]:
np.set_printoptions(threshold=sys.maxsize)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr=np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
arr[0:2,2]

array([3, 8])