# Assignment 1

50 methods of Numpy

In [1]:
!conda install numpy

Solving environment: ...working... done

# All requested packages already installed.



In [3]:
numpy.__version__

NameError: name 'numpy' is not defined

In [4]:
import numpy as np

In [9]:
np.__version__

'1.18.1'

In [8]:
!pip install --upgrade numpy

Requirement already up-to-date: numpy in c:\users\sajid\anaconda3\lib\site-packages (1.19.4)


In [1]:
import numpy as np

In [2]:
np.__version__    #The version has been updated

'1.19.2'

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [4]:
type(x)

numpy.ndarray

## Create one dimensional array

In [5]:
a=[x for x in range(1,11)]             #1

In [6]:
arr=np.array(a)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Create two dimensional array

In [11]:
a=[[1,2,3],[4,5,6],[7,8,9]]           #2
arr1=np.array(a)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# to find dimensisons of array              #3
print("Dimension of first array",arr.ndim),
print("Dimension of Second array",arr1.ndim)
# arr1.ndim

Dimension of first array 1
Dimension of Second array 2


In [16]:
# Shpae of array                       #4
print("Shape of first array",arr.shape),
print("Shape of Second array",arr1.shape)

Shape of first array (10,)
Shape of Second array (3, 3)


In [23]:
# Zeros                                #5
arr=np.zeros(5)    #one dimension zeros
print("arr= \n",arr)
arr1=np.zeros((3,4))  #two dimension zeros
print("arr1= \n",arr1)

arr= 
 [0. 0. 0. 0. 0.]
arr1= 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
# Ones                                #6
arr=np.ones(5)    #one dimension ones
print("arr= \n",arr)
arr1=np.ones((3,4))  #two dimension ones
print("arr1= \n",arr1)

arr= 
 [1. 1. 1. 1. 1.]
arr1= 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
#Eye function                                          7
# It make diagonal elements 1 and rest 0
arr =np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
arr=np.eye(5,7)    # it start from left
arr

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [33]:
# Diagonal function with provided list      8
arr=np.diag([1,3,5,7,9])
arr

array([[1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 9]])

In [34]:
np.diag(arr)

array([1, 3, 5, 7, 9])

In [10]:
# randint                                     9
import numpy as np
# arr=np.random.randint(min,max,total_values)      syntax
arr=np.random.randint(1,100,4)
arr

array([81, 81, 25, 51])

In [17]:
# np.random.rand generates a random value between 0 to 1
arr=np.random.rand()
arr

0.8114068356951671

In [18]:
# if we need multiple values we will write total number of values in parenthes
arr=np.random.rand(3)
arr

array([0.73184022, 0.35999153, 0.73382108])

In [24]:
# if we need multiple values we will write total number of values in parenthes
arr=np.random.rand(3)
arr*10//1

array([1., 9., 4.])

In [25]:
# we can also create two dimensional array using rand 
arr=np.random.rand(2,3)
arr

array([[0.45407924, 0.52424382, 0.55742047],
       [0.22708646, 0.53774366, 0.89792128]])

In [27]:
# 111111 using randn we can create a random number close to zero
# it also generate - number
arr=np.random.randn(3)
arr

array([ 0.47102875, -0.16890489,  1.06091424])

### array indexing and slicing 

In [31]:
#  array_name[start:end,step]
# indexing starts from 0 and ends at length -1
#         0  1   2   3   4
# arr= [  1, 2,  3,  4,  5]
#        -5 -4  -3  -2  -1

# slicing always move from left to right
li=list(range(0,10))
arr=np.array(li)
arr
arr1=arr[2:5]
arr1


array([2, 3, 4])

In [32]:
arr2=arr[-5:-2]
arr2

array([5, 6, 7])

In [33]:
arr3=arr[4:]
arr3

array([4, 5, 6, 7, 8, 9])

In [34]:
arr4=arr[:4]
arr4

array([0, 1, 2, 3])

In [35]:
arr5=arr[-1:-5:-1]
arr5

array([9, 8, 7, 6])

##  Reshape

In [37]:
arr=np.random.randint(1,100,12)
arr

array([97, 86, 91, 49, 85, 83, 12,  3, 43, 78, 63, 84])

In [43]:
arr=arr.reshape(3,4)
arr

array([[49, 35, 18, 69],
       [ 3, 99, 19, 61],
       [90, 20,  5, 71]])

In [44]:
# arr=np.random.randint(1,100,12)
arr = arr.reshape(2,6)
arr

array([[49, 35, 18, 69,  3, 99],
       [19, 61, 90, 20,  5, 71]])

In [45]:
arr=arr.reshape(4,3)
arr

array([[49, 35, 18],
       [69,  3, 99],
       [19, 61, 90],
       [20,  5, 71]])

In [47]:
arr=arr.reshape(12)
arr

array([49, 35, 18, 69,  3, 99, 19, 61, 90, 20,  5, 71])

In [52]:
arr=np.random.randint(1,100,11)
arr=arr.reshape(6,2)
arr         # it will give error

ValueError: cannot reshape array of size 11 into shape (6,2)

In [2]:
import numpy as np
arr=np.array(list(range(1,11)))
arr=np.random.randint(1,100,12)
arr

array([94, 61, 16, 62, 46, 72, 82, 10, 64, 86, 52, 16])

In [3]:
arr=arr.reshape(6,-1)
arr

array([[94, 61],
       [16, 62],
       [46, 72],
       [82, 10],
       [64, 86],
       [52, 16]])

In [4]:
arr=arr.reshape(3,-1)
arr

array([[94, 61, 16, 62],
       [46, 72, 82, 10],
       [64, 86, 52, 16]])

In [6]:
arr=arr.reshape(4,-1)
arr

array([[94, 61, 16],
       [62, 46, 72],
       [82, 10, 64],
       [86, 52, 16]])

In [8]:
arr=arr.reshape(12,-1)
arr

array([[94],
       [61],
       [16],
       [62],
       [46],
       [72],
       [82],
       [10],
       [64],
       [86],
       [52],
       [16]])

## Seed

In [24]:
import numpy as np
# seed function should have a value
# seed function fix the random numbers 
np.random.seed(0)
arr=np.random.randint(1,100,12)
arr

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89])

In [43]:
# creating two dimensional list using for loop
import numpy as np
matrix=[]
for i in range(3):
    a=[]
    for j in range(3):
        num=np.random.randint(0,100,1)
        a.append(j+num)
    matrix.append(a)
arr=np.array(matrix)
print("Dimension of arr1 =", arr.ndim)
arr

Dimension of arr1 = 3


array([[[41],
        [36],
        [66]],

       [[95],
        [70],
        [96]],

       [[ 0],
        [51],
        [38]]])

In [34]:
print(type(arr))
print(arr.shape)

<class 'numpy.ndarray'>
(3, 3, 1)


In [42]:
# creating two dimensional list using for loop
import numpy as np
matrix=[]
for i in range(3):
    for j in range(3):
        num=np.random.randint(0,100,1)
        matrix.append(j+num)
#     matrix.append(a)
arr=np.array(matrix)
arr1=arr.reshape(3,-1)
print("Dimension of arr1 =", arr1.ndim)
arr1

Dimension of arr1 = 2


array([[99, 59, 25],
       [79, 14, 87],
       [48, 50, 71]])