# Assignment 1

50 methods of Numpy

In [1]:
!conda install numpy

Solving environment: ...working... done

# All requested packages already installed.



In [3]:
numpy.__version__

NameError: name 'numpy' is not defined

In [4]:
import numpy as np

In [9]:
np.__version__

'1.18.1'

In [8]:
!pip install --upgrade numpy

Requirement already up-to-date: numpy in c:\users\sajid\anaconda3\lib\site-packages (1.19.4)


In [1]:
import numpy as np

In [2]:
np.__version__    #The version has been updated

'1.19.2'

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [4]:
type(x)

numpy.ndarray

## Create one dimensional array

In [5]:
a=[x for x in range(1,11)]             #1

In [6]:
arr=np.array(a)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Create two dimensional array

In [11]:
a=[[1,2,3],[4,5,6],[7,8,9]]           #2
arr1=np.array(a)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# to find dimensisons of array              #3
print("Dimension of first array",arr.ndim),
print("Dimension of Second array",arr1.ndim)
# arr1.ndim

Dimension of first array 1
Dimension of Second array 2


In [16]:
# Shpae of array                       #4
print("Shape of first array",arr.shape),
print("Shape of Second array",arr1.shape)

Shape of first array (10,)
Shape of Second array (3, 3)


In [23]:
# Zeros                                #5
arr=np.zeros(5)    #one dimension zeros
print("arr= \n",arr)
arr1=np.zeros((3,4))  #two dimension zeros
print("arr1= \n",arr1)

arr= 
 [0. 0. 0. 0. 0.]
arr1= 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
