# Assignment 1

50 methods of Numpy

In [1]:
!conda install numpy

Solving environment: ...working... done

# All requested packages already installed.



In [3]:
numpy.__version__

NameError: name 'numpy' is not defined

In [4]:
import numpy as np

In [9]:
np.__version__

'1.18.1'

In [8]:
!pip install --upgrade numpy

Requirement already up-to-date: numpy in c:\users\sajid\anaconda3\lib\site-packages (1.19.4)


In [1]:
import numpy as np

In [2]:
np.__version__    #The version has been updated

'1.19.2'

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [4]:
type(x)

numpy.ndarray

## Create one dimensional array

In [5]:
a=[x for x in range(1,11)]             #1

In [6]:
arr=np.array(a)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Create two dimensional array

In [11]:
a=[[1,2,3],[4,5,6],[7,8,9]]           #2
arr1=np.array(a)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# to find dimensisons of array              #3
print("Dimension of first array",arr.ndim),
print("Dimension of Second array",arr1.ndim)
# arr1.ndim

Dimension of first array 1
Dimension of Second array 2


In [16]:
# Shpae of array                       #4
print("Shape of first array",arr.shape),
print("Shape of Second array",arr1.shape)

Shape of first array (10,)
Shape of Second array (3, 3)


In [23]:
# Zeros                                #5
arr=np.zeros(5)    #one dimension zeros
print("arr= \n",arr)
arr1=np.zeros((3,4))  #two dimension zeros
print("arr1= \n",arr1)

arr= 
 [0. 0. 0. 0. 0.]
arr1= 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
# Ones                                #6
arr=np.ones(5)    #one dimension ones
print("arr= \n",arr)
arr1=np.ones((3,4))  #two dimension ones
print("arr1= \n",arr1)

arr= 
 [1. 1. 1. 1. 1.]
arr1= 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
#Eye function                                          7
# It make diagonal elements 1 and rest 0
arr =np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
arr=np.eye(5,7)    # it start from left
arr

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [33]:
# Diagonal function with provided list      8
arr=np.diag([1,3,5,7,9])
arr

array([[1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 9]])

In [34]:
np.diag(arr)

array([1, 3, 5, 7, 9])

In [10]:
# randint                                     9
import numpy as np
# arr=np.random.randint(min,max,total_values)      syntax
arr=np.random.randint(1,100,4)
arr

array([81, 81, 25, 51])

In [17]:
# np.random.rand generates a random value between 0 to 1
arr=np.random.rand()
arr

0.8114068356951671

In [18]:
# if we need multiple values we will write total number of values in parenthes
arr=np.random.rand(3)
arr

array([0.73184022, 0.35999153, 0.73382108])

In [24]:
# if we need multiple values we will write total number of values in parenthes
arr=np.random.rand(3)
arr*10//1

array([1., 9., 4.])

In [25]:
# we can also create two dimensional array using rand 
arr=np.random.rand(2,3)
arr

array([[0.45407924, 0.52424382, 0.55742047],
       [0.22708646, 0.53774366, 0.89792128]])