# Assignment 1

50 methods of Numpy

In [1]:
!conda install numpy

Solving environment: ...working... done

# All requested packages already installed.



In [3]:
numpy.__version__

NameError: name 'numpy' is not defined

In [4]:
import numpy as np

In [9]:
np.__version__

'1.18.1'

In [8]:
!pip install --upgrade numpy

Requirement already up-to-date: numpy in c:\users\sajid\anaconda3\lib\site-packages (1.19.4)


In [1]:
import numpy as np

In [2]:
np.__version__    #The version has been updated

'1.19.2'

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [4]:
type(x)

numpy.ndarray

## 1 : Create one dimensional array

In [5]:
a=[x for x in range(1,11)]             #1

In [6]:
arr=np.array(a)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2 : Create two dimensional array

In [11]:
a=[[1,2,3],[4,5,6],[7,8,9]]           #2
arr1=np.array(a)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 3 : find dimensisons of array  

In [15]:
            #3
print("Dimension of first array",arr.ndim),
print("Dimension of Second array",arr1.ndim)
# arr1.ndim

Dimension of first array 1
Dimension of Second array 2


## 4 : shape of array

In [16]:
# Shpae of array                       #4
print("Shape of first array",arr.shape),
print("Shape of Second array",arr1.shape)

Shape of first array (10,)
Shape of Second array (3, 3)


## 5 : zeros

In [23]:
# Zeros                                #5
arr=np.zeros(5)    #one dimension zeros
print("arr= \n",arr)
arr1=np.zeros((3,4))  #two dimension zeros
print("arr1= \n",arr1)

arr= 
 [0. 0. 0. 0. 0.]
arr1= 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 6 : ones

In [25]:
# Ones                                #6
arr=np.ones(5)    #one dimension ones
print("arr= \n",arr)
arr1=np.ones((3,4))  #two dimension ones
print("arr1= \n",arr1)

arr= 
 [1. 1. 1. 1. 1.]
arr1= 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 7 : eye function

In [27]:
#Eye function                                          7
# It make diagonal elements 1 and rest 0
arr =np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
arr=np.eye(5,7)    # it start from left
arr

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

## 8 : diag method

In [33]:
# Diagonal function with provided list      8
arr=np.diag([1,3,5,7,9])
arr

array([[1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 9]])

In [34]:
np.diag(arr)

array([1, 3, 5, 7, 9])

## 9 : randint

In [10]:
# randint                                     9
import numpy as np`
# arr=np.random.randint(min,max,total_values)      syntax
arr=np.random.randint(1,100,4)
arr

array([81, 81, 25, 51])

## 10 : rand

In [17]:
# np.random.rand generates a random value between 0 to 1
arr=np.random.rand()
arr

0.8114068356951671

In [18]:
# if we need multiple values we will write total number of values in parenthes
arr=np.random.rand(3)
arr

array([0.73184022, 0.35999153, 0.73382108])

In [24]:
# if we need multiple values we will write total number of values in parenthes
arr=np.random.rand(3)
arr*10//1

array([1., 9., 4.])

In [25]:
# we can also create two dimensional array using rand 
arr=np.random.rand(2,3)
arr

array([[0.45407924, 0.52424382, 0.55742047],
       [0.22708646, 0.53774366, 0.89792128]])

## 11 : randn

In [27]:
# 111111 using randn we can create a random number close to zero
# it also generate - number
arr=np.random.randn(3)
arr

array([ 0.47102875, -0.16890489,  1.06091424])

## 12 : array indexing

In [21]:
# indexing starts from 0 and ends at length -1
#         0  1   2   3   4
# arr= [  1, 2,  3,  4,  5]
#        -5 -4  -3  -2  -1
arr=np.array([1,2,3,4,5,6,7,8,9])
print("index 2 = ",arr[2],"& index 5 =",arr[5])

index 2 =  3 & index 5 = 6


## 13 : array slicing

In [31]:
#  array_name[start:end,step]
# slicing always move from left to right
li=list(range(0,10))
arr=np.array(li)
arr
arr1=arr[2:5]
arr1


array([2, 3, 4])

In [32]:
arr2=arr[-5:-2]
arr2

array([5, 6, 7])

In [33]:
arr3=arr[4:]
arr3

array([4, 5, 6, 7, 8, 9])

In [34]:
arr4=arr[:4]
arr4

array([0, 1, 2, 3])

In [35]:
arr5=arr[-1:-5:-1]
arr5

array([9, 8, 7, 6])

##  14 : Reshape

In [37]:
arr=np.random.randint(1,100,12)
arr

array([97, 86, 91, 49, 85, 83, 12,  3, 43, 78, 63, 84])

In [43]:
arr=arr.reshape(3,4)
arr

array([[49, 35, 18, 69],
       [ 3, 99, 19, 61],
       [90, 20,  5, 71]])

In [44]:
# arr=np.random.randint(1,100,12)
arr = arr.reshape(2,6)
arr

array([[49, 35, 18, 69,  3, 99],
       [19, 61, 90, 20,  5, 71]])

In [45]:
arr=arr.reshape(4,3)
arr

array([[49, 35, 18],
       [69,  3, 99],
       [19, 61, 90],
       [20,  5, 71]])

In [47]:
arr=arr.reshape(12)
arr

array([49, 35, 18, 69,  3, 99, 19, 61, 90, 20,  5, 71])

In [52]:
arr=np.random.randint(1,100,11)
arr=arr.reshape(6,2)
arr         # it will give error

ValueError: cannot reshape array of size 11 into shape (6,2)

In [2]:
import numpy as np
arr=np.array(list(range(1,11)))
arr=np.random.randint(1,100,12)
arr

array([94, 61, 16, 62, 46, 72, 82, 10, 64, 86, 52, 16])

In [3]:
arr=arr.reshape(6,-1)
arr

array([[94, 61],
       [16, 62],
       [46, 72],
       [82, 10],
       [64, 86],
       [52, 16]])

In [4]:
arr=arr.reshape(3,-1)
arr

array([[94, 61, 16, 62],
       [46, 72, 82, 10],
       [64, 86, 52, 16]])

In [6]:
arr=arr.reshape(4,-1)
arr

array([[94, 61, 16],
       [62, 46, 72],
       [82, 10, 64],
       [86, 52, 16]])

In [8]:
arr=arr.reshape(12,-1)
arr

array([[94],
       [61],
       [16],
       [62],
       [46],
       [72],
       [82],
       [10],
       [64],
       [86],
       [52],
       [16]])

## 15 : Seed

In [24]:
import numpy as np
# seed function should have a value
# seed function fix the random numbers 
np.random.seed(0)
arr=np.random.randint(1,100,12)
arr

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89])

In [43]:
# creating two dimensional list using for loop
import numpy as np
matrix=[]
for i in range(3):
    a=[]
    for j in range(3):
        num=np.random.randint(0,100,1)
        a.append(j+num)
    matrix.append(a)
arr=np.array(matrix)
print("Dimension of arr1 =", arr.ndim)
arr

Dimension of arr1 = 3


array([[[41],
        [36],
        [66]],

       [[95],
        [70],
        [96]],

       [[ 0],
        [51],
        [38]]])

In [34]:
print(type(arr))
print(arr.shape)

<class 'numpy.ndarray'>
(3, 3, 1)


In [42]:
# creating two dimensional list using for loop
import numpy as np
matrix=[]
for i in range(3):
    for j in range(3):
        num=np.random.randint(0,100,1)
        matrix.append(j+num)
#     matrix.append(a)
arr=np.array(matrix)
arr1=arr.reshape(3,-1)
print("Dimension of arr1 =", arr1.ndim)
arr1

Dimension of arr1 = 2


array([[99, 59, 25],
       [79, 14, 87],
       [48, 50, 71]])

In [46]:
# indexing
arr1[1,1]

14

In [47]:
arr1[1][0]

79

## 16 : 2 dimensional array slicing

In [ ]:
# 2 dimensional array slicing

In [54]:
arr1[1:,2:]

array([[87],
       [71]])

In [57]:
np.random.seed(1)
arr=np.random.randint(1,500,30).reshape(6,5)
arr

array([[ 38, 236, 397,  73, 256],
       [394, 204, 134, 336, 449],
       [145, 130, 461,  72, 238],
       [391, 282, 179, 277, 255],
       [358, 403, 469, 396, 253],
       [491, 157, 414, 399,  51]])

In [58]:
arr[2:-1,:3]

array([[145, 130, 461],
       [391, 282, 179],
       [358, 403, 469]])

In [61]:
arr[2:,-2:]

array([[ 72, 238],
       [277, 255],
       [396, 253],
       [399,  51]])

## 17 : arange

In [1]:
import numpy as np

In [3]:
arr=np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
arr>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

## 18 : conditional selection

In [6]:
# Conditional selectioin
b=arr[arr>10]
b

array([11, 12, 13, 14, 15])

In [10]:
arr[arr%2==0]=0
arr

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15])

In [11]:
arr[2:-4]

array([ 3,  0,  5,  0,  7,  0,  9,  0, 11])

In [1]:
import numpy as np

## 19 : sum mathod

In [3]:
arr=np.random.randint(1,1000,50)
arr

array([851, 203, 330, 149, 636,  47, 771, 377, 259, 282, 846, 533, 362,
       836, 684, 923, 545, 954, 563, 200, 794, 252, 325,  12, 306, 241,
       498,  14, 548, 938, 619, 225, 399, 438, 902, 384, 278,  55, 687,
       134, 947, 499, 449, 991, 278, 848, 313, 200, 634, 317])

In [10]:
arr[arr>300].sum()

21047

## 20 : size 

In [14]:
arr[arr>180].size

44

In [35]:
import numpy as np
li=range(1,101)
# arr=np.array(li)
arr=np.array(li).size
print(arr)
arr1=np.arange(1,501).size
arr1

100


500

##  21 : itemsize

In [43]:
# the size in bytes of each element of the array.
arr=np.arange(1,51)
arr.itemsize

8

## 22: ndarray.type and dtype

In [44]:
arr=np.arange(1,11)
print(type(arr))
arr.dtype


<class 'numpy.ndarray'>


dtype('int64')

In [46]:
# The type of the array can also be explicitly specified at creation time:

c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

## 23 : np.empty

In [63]:
arr=np.empty(1)
arr1=np.empty(4)
arr2=np.empty((2,4))
arr3=np.empty((2,0))   ## if any value is 0 it will create an empty array
arr4=np.empty((0,2))
print("arr = " ,arr, "shape = " , arr.shape)
print("arr1 = ",arr1,"shape = ", arr1.shape)
print("arr2 = ",arr2,"shape = ", arr2.shape)
print("arr3 = ",arr3,"shape = ", arr3.shape)
print("arr4 = ",arr4,"shape = ", arr4.shape)
print(arr.dtype)

arr =  [6.91817212e-310] shape =  (1,)
arr1 =  [1. 2. 3. 4.] shape =  (4,)
arr2 =  [[4.67299121e-310 0.00000000e+000 1.78488218e+161 2.51715952e+180]
 [1.40022644e+195 1.05774260e-153 1.12044105e+219 6.91817212e-310]] shape =  (2, 4)
arr3 =  [] shape =  (2, 0)
arr4 =  [] shape =  (0, 2)
float64


## 24 : np.linespace 

In [76]:
#Return evenly spaced numbers over a specified interval
# using np.arange we can create an array of integers but 
# what is we need floating point number's array
# let suppose
arr=np.arange(10,30,5)
print(arr)
arr=np.arange(0,3,0.3)
print(arr) 

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7]


In [80]:
# generally due to float precesion it is not predicted number of elements so
# it is usually better to use the function linspace that receives as an argument
# the number of elements that we want, instead of the step:
arr=np.linspace(0,3,9)  # in the last we tell number of elements instead step
arr

array([0.   , 0.375, 0.75 , 1.125, 1.5  , 1.875, 2.25 , 2.625, 3.   ])

In [82]:
arr=np.arange(3,4)
print(arr)

[3]


## 25 : default random number generator

In [84]:
rg = np.random.default_rng(1)

In [86]:
a = np.floor(10*rg.random((3,4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

## 26 : resize

In [106]:
# np.resize(array,(row,col))
arr=np.array([[1,2],[3,4]])
print(arr.shape)
print(type(arr))

(2, 2)
<class 'numpy.ndarray'>


In [107]:
np.resize(arr,(2,3))

array([[1, 2, 3],
       [4, 1, 2]])

In [108]:
np.resize(arr,(1,3))

array([[1, 2, 3]])

In [109]:
np.resize(arr,(3,2))

array([[1, 2],
       [3, 4],
       [1, 2]])

In [110]:
np.resize(arr,(3,1))

array([[1],
       [2],
       [3]])

## 27 : np.ravel

In [127]:
# It is equivalent to reshape(-1, order=order).
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [128]:
x.reshape(-1)

array([1, 2, 3, 4, 5, 6])

## 28 : astype

In [116]:
x=np.array([1 , 2.5 , 3.3 , 4.6])
x

array([1. , 2.5, 3.3, 4.6])

In [118]:
x.astype(int)        ## it converts the type of the array

array([1, 2, 3, 4])

## 29 : arithmetic operations

In [119]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
b=arr+2
b

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [122]:
arr   # will not change the original array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
c=arr*5
c

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [126]:
d=arr**2
d

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

## 30 : np.prod

In [132]:
#  it multiplicate the elements of the array
arr=np.arange(1,5)
arr.prod()

24

In [133]:
arr=np.arange(1,11)
arr.prod()

3628800

In [146]:
# The product of an empty array is the neutral element 1:
np.prod([])

1.0

## 31 : np.floor

In [134]:
arr=np.random.randn(5)
arr

array([ 1.08215952,  0.76427971, -0.62044153,  1.09015846, -0.39725873])

In [137]:
np.floor(arr)

array([ 1.,  0., -1.,  1., -1.])

In [158]:
arr=np.linspace(1,6,12)
arr

array([1.        , 1.45454545, 1.90909091, 2.36363636, 2.81818182,
       3.27272727, 3.72727273, 4.18181818, 4.63636364, 5.09090909,
       5.54545455, 6.        ])

In [159]:
np.floor(arr)

array([1., 1., 1., 2., 2., 3., 3., 4., 4., 5., 5., 6.])

In [160]:
np.floor(np.linspace(1,5,7))

array([1., 1., 2., 3., 3., 4., 5.])

## 32 : np.ceil 

In [141]:
arr=np.random.randn(5)

In [142]:
arr

array([-0.0783936 , -0.1992076 ,  1.21912595, -0.95284712, -0.22719039])

In [143]:
np.ceil(arr)

array([-0., -0.,  2., -0., -0.])

In [156]:
arr=np.linspace(1,6,12)
arr

array([1.        , 1.45454545, 1.90909091, 2.36363636, 2.81818182,
       3.27272727, 3.72727273, 4.18181818, 4.63636364, 5.09090909,
       5.54545455, 6.        ])

In [157]:
np.ceil(arr)

array([1., 2., 2., 3., 3., 4., 4., 5., 5., 6., 6., 6.])

## 33 : np.trunc

In [144]:
# Return the truncated value of the input, element-wise.
arr=np.random.randn(5)
arr

array([-1.56932595, -0.10982129, -1.56828036, -0.95373434,  1.39633472])

In [145]:
np.trunc(arr)

array([-1., -0., -1., -0.,  1.])

## 34 : np.rint

In [148]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.rint(a)

array([-2., -2., -0.,  0.,  2.,  2.,  2.])

## 35 : np.fromfunction

In [149]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [151]:
arr=np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
arr

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [153]:
arr=np.fromfunction(lambda i, j: i - j, (3, 3), dtype=int)
arr

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

## 36 : np.geomspace 

In [163]:
np.geomspace(1,100,4)

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [165]:
np.geomspace(1,1000,10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

##  37 : np.identity

In [167]:
arr=np.eye(5,7)
arr

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [174]:
np.identity(3 ,dtype=bool)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [175]:
np.identity(3 ,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [176]:
np.identity(3) # by default it will be float

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##  38 : np.ones_like

In [184]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [185]:
b=arr.reshape(2,3)

In [186]:
np.ones_like(b)

array([[1, 1, 1],
       [1, 1, 1]])