In [1]:
import numpy as np

In [4]:
def function1():
    x=np.arange(1,13).reshape((6,2))
    return x

In [5]:
function1()

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [6]:
    #create 3D array (3,3,3)
    #must data type should have float64
    #array value should be satart from 10 and end with 36 (both included)
    # Hint: dtype, reshape 

In [35]:
def function2():
    x=            np.arange(10,37,dtype=np.float64).reshape((3,3,3))
    return x

In [36]:
x=np.arange(10,37).size
x

27

In [37]:
function2()

array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]],

       [[28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]]])

In [38]:
#task3
def function3():
    #extract those numbers from given array. those are must exist in 5,7 Table
    #example [35,70,105,..]
    a = np.arange(1, 100*10+1).reshape((100,10))
    x = a[(a%5==0) & (a%7==0)] #wrtie your code here
    return x
    """
    Expected Output:
     [35,  70, 105, 140, 175, 210, 245, 280, 315, 350, 385, 420, 455,
       490, 525, 560, 595, 630, 665, 700, 735, 770, 805, 840, 875, 910,
       945, 980] 
    """ 

In [39]:
function3()

array([ 35,  70, 105, 140, 175, 210, 245, 280, 315, 350, 385, 420, 455,
       490, 525, 560, 595, 630, 665, 700, 735, 770, 805, 840, 875, 910,
       945, 980])

In [78]:
#task4
def function4():
    #Swap columns 1 and 2 in the array arr.
   
    arr = np.arange(9).reshape(3,3)
  
    return arr[:,[1,0,2]]  #wrtie your code here
    """
    Expected Output:
          array([[1, 0, 2],
                [4, 3, 5],
                [7, 6, 8]])
    """ 
    

In [79]:
function4()

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [151]:
#task4
def function41():
    #Swap columns 1 and 2 in the array arr.
   
    arr = np.arange(9).reshape(3,3)
  
    return np.swapaxes(arr,0,1)  #wrtie your code here
    """
    Expected Output:
          array([[1, 0, 2],
                [4, 3, 5],
                [7, 6, 8]])
    """ 
    

In [152]:
function41()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [2]:
import numpy as np
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [70]:
np.swapaxes(arr[:,[0,1]],axis1=0,axis2=1)

array([[0, 3, 6],
       [1, 4, 7]])

In [80]:
#task5
def function5():
    #Create a null vector of size 20 with 4 rows and 5 columns with numpy function
   
    z = np.zeros((4,5),dtype=int) #wrtie your code here
  
    return z
    """
    Expected Output:
          array([[0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0]])
    """ 


In [81]:
function5()

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
#task6
def function6():
    # Create a null vector of size 10 but the fifth and eighth value which is 10,20 respectively
   
    arr =np.zeros((10), dtype=int)
    arr[4]=10
    arr[7]=20
     
    #wrtie your code here
  
    return arr
   

In [12]:
function6()

array([ 0,  0,  0,  0, 10,  0,  0, 20,  0,  0])

In [55]:
#task7
def function7():
    #  Create an array of zeros with the same shape and type as X. Dont use reshape method
    x = np.arange(4, dtype=np.int64)
  
    return np.zeros_like(x) #write your code here

    """
    Expected Output:
          array([0, 0, 0, 0], dtype=int64)
    """ 


In [56]:
function7()

array([0, 0, 0, 0])

In [57]:

#task8
def function8():
    # Create a new array of 2x5 uints, filled with 6.
    
    x = np.full((2,5),6) #write your code here
  
    return x


In [58]:
function8()

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [62]:
#task8
def function8():
    # Create a new array of 2x5 uints, filled with 6.
    
    x = np.full((2,5),6) #write your code here
  
    return x

    """
    Expected Output:
    
              array([[6, 6, 6, 6, 6],
                     [6, 6, 6, 6, 6]], dtype=uint32)
     """ 


In [63]:
function8()

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [96]:
#task9
def function9():
    # Create an array of 2, 4, 6, 8, ..., 100.
    
    a =np.arange(2,101,2) # write your code here
  
    return a


    """
       Expected Output:
              array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
                    28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
                    54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
                    80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])
     """ 




In [97]:
function9()

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [106]:
#task10
def function10():
    # Subtract the 1d array brr from the 2d array arr, such that each item of brr subtracts from respective row of arr.
    
    arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
    brr = np.array([1,2,3])
    subt = arr-brr[:,None] # write your code here 
  
    return subt
    """
     Expected Output:
               array([[2 2 2]
                      [2 2 2]
                      [2 2 2]])
     """ 
    
    


In [107]:
function10()

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [124]:
#task11
def function11():
    # Replace all odd numbers in arr with -1 without changing arr.
    
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    ans = arr[arr%2!=0]=-1 #write your code here 
  
    return ans

    """
     Expected Output:
              array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
     """ 


In [125]:
function11()

-1

In [132]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ans=arr[arr%2!=0]=-1

In [133]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [145]:
#task11
def function11():
    # Replace all odd numbers in arr with -1 without changing arr.
    
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    ans = arr[:].copy() 
    ans[ans%2!=0]=-1
  
    return ans

    """
     Expected Output:
              array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
     """ 


In [146]:
function11()

arr =  [0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [138]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [203]:
def function12():
    # Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.
    # HINT: use stacking concept
    
    arr = np.array([1,2,3])
    ans = np.hstack((np.vstack((arr,arr,arr)).T.flatten(),np.hstack((arr,arr,arr)).flatten())) #write your code here 
#     np.vstack((arr,ans))
    return ans

    """
     Expected Output:
              array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
     """ 


In [204]:
function12()

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [172]:
arr = np.array([1,2,3])

In [173]:
arr

array([1, 2, 3])

In [176]:
np.hstack((arr,arr,arr))

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [197]:
a=np.vstack((arr,arr,arr)).T.flatten()
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [199]:
b=np.hstack((arr,arr,arr)).flatten()
b

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [200]:
np.hstack((a,b))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [210]:
def function122():
    # Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.
    # HINT: use stacking concept
    
    arr = np.array([1,2,3])
    ans = np.hstack((np.vstack((arr,arr,arr)).T.flatten(),np.hstack((arr,arr,arr)).flatten())) #write your code here 
#     np.vstack((arr,ans))
    return ans

    """
     Expected Output:
              array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
     """ 


In [211]:
function122()

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [9]:
def function13():
    # Set a condition which gets all items between 5 and 10 from arr.
    
    
    arr = np.array([2, 6, 1, 9, 10, 3, 27])
    ans = arr[(arr>5) & (arr<10)] #write your code here 
  
    return ans

    """
     Expected Output:
              array([6, 9])
     """ 


In [10]:
function13()

array([6, 9])