In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 15.3 ms, sys: 14.9 ms, total: 30.2 ms
Wall time: 58.3 ms


In [7]:
%time for _ in range(10): my_list2=[x*2 for x in my_list]

CPU times: user 454 ms, sys: 76.3 ms, total: 530 ms
Wall time: 530 ms


# axis in numpy

In [8]:
arr=np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
arr.min(axis=0)

array([0, 1, 2, 3])

In [10]:
arr.min(axis=1)

array([ 0,  4,  8, 12])

In [11]:
# during stacking and spliting

In [12]:
np.split(arr,2,axis=0,)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [16]:
brr=np.arange(16,32).reshape(4,4)
brr

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [17]:
np.concatenate((arr,brr),axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [18]:
np.concatenate((arr,brr),axis=1)

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [21]:
np.split(arr,[2,3],axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [22]:
np.split(arr,[2,3],axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

# let's Start book appendix a

In [3]:
import numpy as np

In [8]:
arr=np.arange((4*4* 2*2)).reshape(4,4, 2,2)

In [9]:
arr

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]],


       [[[32, 33],
         [34, 35]],

        [[36, 37],
         [38, 39]],

        [[40, 41],
         [42, 43]],

        [[44, 45],
         [46, 47]]],


       [[[48, 49],
         [50, 51]],

        [[52, 53],
         [54, 55]],

        [[56, 57],
         [58, 59]],

        [[60, 61],
         [62, 63]]]])

In [12]:
arr[-1,1]

array([[52, 53],
       [54, 55]])

In [15]:
np.ones((3, 4, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [14]:
np.ones((3, 4, 5)).strides

(160, 40, 8)

# section 2

In [20]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
arr.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
arr.reshape((3,4),order="C")

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
arr.reshape((3,4),order="F")

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

# np.ravel

In [34]:
arr=np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
arr.ravel()   #similar to C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
arr.ravel("C")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
arr.ravel("F")

array([ 0,  3,  6,  9,  1,  4,  7, 10,  2,  5,  8, 11])

## np.r_ and c_

In [45]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [61]:
arr1 = arr.reshape((3, 2))
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [62]:
brr=np.arange(36).reshape(6,6)
brr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [63]:
np.vstack((brr,arr))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [ 0,  1,  2,  3,  4,  5]])

In [64]:
np.c_[brr,arr]

array([[ 0,  1,  2,  3,  4,  5,  0],
       [ 6,  7,  8,  9, 10, 11,  1],
       [12, 13, 14, 15, 16, 17,  2],
       [18, 19, 20, 21, 22, 23,  3],
       [24, 25, 26, 27, 28, 29,  4],
       [30, 31, 32, 33, 34, 35,  5]])

In [53]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)

In [54]:
np.r_[arr1,arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.60812982, -1.83011682],
       [ 0.474725  ,  0.16454947],
       [ 1.68498239,  1.5891708 ]])

In [56]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [57]:
np.r_[1:6, -10:-5]

array([  1,   2,   3,   4,   5, -10,  -9,  -8,  -7,  -6])

## np.repeat and tile

In [65]:
arr=np.array([1,2,3])
arr.repeat(3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [66]:
np.repeat((arr),3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [70]:
arr.repeat([2,1,4])   #each element has to repeat how many time

array([1, 1, 2, 3, 3, 3, 3])

In [71]:
arr=np.arange(4).reshape(2,2)
arr

array([[0, 1],
       [2, 3]])

In [72]:
arr.repeat(3,axis=0)

array([[0, 1],
       [0, 1],
       [0, 1],
       [2, 3],
       [2, 3],
       [2, 3]])

In [73]:
arr.repeat(3,axis=1)

array([[0, 0, 0, 1, 1, 1],
       [2, 2, 2, 3, 3, 3]])

In [75]:
arr.repeat([3,5],axis=0)

array([[0, 1],
       [0, 1],
       [0, 1],
       [2, 3],
       [2, 3],
       [2, 3],
       [2, 3],
       [2, 3]])

In [76]:
arr.repeat([3,5],axis=1)

array([[0, 0, 0, 1, 1, 1, 1, 1],
       [2, 2, 2, 3, 3, 3, 3, 3]])

In [77]:
arr

array([[0, 1],
       [2, 3]])

In [85]:
np.tile(arr,[4,2])   #row and columns with given array

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])

In [89]:
np.tile(arr,(2,3))  #we can pass tuple as well

array([[0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3]])