Q1 Import numpy as np and print the version number.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

Q. Create a 1D array of numbers from 0 to 9

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q. Create a 3×3 numpy array of all True’s

In [4]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Q. Extract all odd numbers from arr

In [6]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# there are two methods to do this 
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [8]:
arr[~(arr%2==0)]

array([1, 3, 5, 7, 9])

Q. Replace all odd numbers in arr with -1

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Q. Replace all odd numbers in arr with -1 without changing arr

In [11]:
arr=np.arange(10)
arr1=arr[:].copy()

In [12]:
arr1[arr1%2==1]=-1
arr1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
brr=np.where(arr%2!=0,-1,arr)  # second method
brr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q. Convert a 1D array to a 2D array with 2 rows

In [ ]:
arr=np.arange(10)
arr

In [ ]:
arr.reshape(2,5)

Q. Stack arrays a and b vertically

In [ ]:
a=np.arange(10).reshape(2,-1)
a

In [ ]:
b=np.repeat(1,10).reshape(2,-1)
b

In [ ]:
np.vstack((a,b))

9. How to stack two arrays horizontally?

In [ ]:
a

In [ ]:
b

In [ ]:
np.hstack((a,b))

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a

In [ ]:
a = np.array([1,2,3])

In [ ]:
np.hstack((np.repeat(a,3),np.tile(a,3))) # one method

In [ ]:
np.r_[np.repeat(a,3),np.tile(a,3)]      # second method

In [ ]:
arr = np.array([1,2,3])                 # third jugad method
np.hstack((np.vstack((arr,arr,arr)).T.flatten(),np.hstack((arr,arr,arr)).flatten()))

Q. Get the common items between a and b

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
b[np.in1d(a,b)]  # but it is giving repeatedely values

In [ ]:
np.intersect1d(a,b)

12. How to remove from one array those items that exist in another?

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [ ]:
np.setdiff1d(a,b)

In [ ]:
a                    # it is just extracting not removing

Q. Get the positions where elements of a and b match

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
np.where(a==b)        #it will return index

In [ ]:
a[0]=7

In [ ]:
np.where(a==b)    # it will return all the occurrences

Q. Get all items between 5 and 10 from a.

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [ ]:
a[(a>=5)&(a<=10)]                  # first method

In [ ]:
index=np.where((a>=5)&(a<=10))     #second method

In [ ]:
a[index]

Q. Convert the function maxx that works on two scalars, to work on two arrays.

In [ ]:
# Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [ ]:
np.maximum(a,b)

Q. Swap columns 1 and 2 in the array arr

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

In [ ]:
arr[:,[1,0,2]]

Q. Swap rows 1 and 2 in the array arr:

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

In [ ]:
arr[[1,0,2],:]

Q. Reverse the rows of a 2D array arr.

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

In [ ]:
arr[::-1]

Q. Reverse the columns of a 2D array arr.

In [ ]:
arr

In [ ]:
arr[:,::-1]

Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [ ]:
arr=np.random.randint(5,10,15).reshape(5,3)   
arr          # it will create random numbers not float but we need float

In [ ]:
arr+np.random.random((5,3))   # after creating we covert in random float

In [ ]:
arr=np.linspace(5,10,15).reshape(5,3)

In [ ]:
arr   # linspace create equal diffrence numbers

In [ ]:
arr=np.random.uniform(low=5,high=10,size=(5,3)) #optional/ we can assign them low and high

In [ ]:
arr

Q. Print or show only 3 decimal places of the numpy array rand_arr.

In [ ]:
rand_arr = np.random.random((5,3))
rand_arr

In [ ]:
np.set_printoptions(precision=3)

In [ ]:
rand_arr

In [ ]:
np.arange(9).reshape(3,3).ndim