Q1 Import numpy as np and print the version number.

In [20]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

Q. Create a 1D array of numbers from 0 to 9

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q. Create a 3×3 numpy array of all True’s

In [4]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Q. Extract all odd numbers from arr

In [3]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# there are two methods to do this 
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [8]:
arr[~(arr%2==0)]

array([1, 3, 5, 7, 9])

Q. Replace all odd numbers in arr with -1

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Q. Replace all odd numbers in arr with -1 without changing arr

In [11]:
arr=np.arange(10)
arr1=arr[:].copy()

In [12]:
arr1[arr1%2==1]=-1
arr1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
brr=np.where(arr%2!=0,-1,arr)  # second method
brr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[np.where(arr%2==0)]

array([0, 2, 4, 6, 8])

Q. Convert a 1D array to a 2D array with 2 rows

In [17]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Q. Stack arrays a and b vertically

In [11]:
a=np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
b=np.repeat(1,10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.concatenate((a,b),axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
np.concatenate((a,b),axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [20]:
np.concatenate??

9. How to stack two arrays horizontally?

In [24]:
np.block([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [22]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a

In [25]:
a = np.array([1,2,3])

In [26]:
np.hstack((np.repeat(a,3),np.tile(a,3))) # one method

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [27]:
np.r_[np.repeat(a,3),np.tile(a,3)]      # second method

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [28]:
arr = np.array([1,2,3])                 # third jugad method
np.hstack((np.vstack((arr,arr,arr)).T.flatten(),np.hstack((arr,arr,arr)).flatten()))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Q. Get the common items between a and b

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [31]:
b[np.in1d(a,b)]  # but it is giving repeatedely values

array([2, 2, 4, 4])

In [32]:
np.intersect1d(a,b)

array([2, 4])

12. How to remove from one array those items that exist in another?

In [33]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [34]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [35]:
a                    # it is just extracting not removing

array([1, 2, 3, 4, 5])

Q. Get the positions where elements of a and b match

In [36]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [38]:
np.where(a==b)        #it will return index

(array([1, 3, 5, 7]),)

In [39]:
a[0]=7

In [40]:
np.where(a==b)    # it will return all the occurrences

(array([0, 1, 3, 5, 7]),)

Q. Get all items between 5 and 10 from a.

In [41]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [42]:
a[(a>=5)&(a<=10)]                  # first method

array([ 6,  9, 10])

In [43]:
index=np.where((a>=5)&(a<=10))     #second method

In [44]:
a[index]

array([ 6,  9, 10])

Q. Convert the function maxx that works on two scalars, to work on two arrays.

In [45]:
# Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [46]:
np.maximum(a,b)

array([6, 7, 9, 8, 9, 7, 5])

Q. Swap columns 1 and 2 in the array arr

In [47]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Q. Swap rows 1 and 2 in the array arr:

In [49]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

Q. Reverse the rows of a 2D array arr.

In [51]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Q. Reverse the columns of a 2D array arr.

In [53]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [55]:
arr=np.random.randint(5,10,15).reshape(5,3)   
arr          # it will create random numbers not float but we need float

array([[9, 8, 7],
       [7, 8, 9],
       [7, 8, 9],
       [6, 5, 6],
       [8, 5, 8]])

In [56]:
arr+np.random.random((5,3))   # after creating we covert in random float

array([[9.15095634, 8.34247509, 7.46591722],
       [7.89030008, 8.01265949, 9.4988596 ],
       [7.01590482, 8.67822788, 9.32942155],
       [6.04973296, 5.12614739, 6.41913084],
       [8.91607802, 5.61501259, 8.58230584]])

In [57]:
arr=np.linspace(5,10,15).reshape(5,3)

In [58]:
arr   # linspace create equal diffrence numbers

array([[ 5.        ,  5.35714286,  5.71428571],
       [ 6.07142857,  6.42857143,  6.78571429],
       [ 7.14285714,  7.5       ,  7.85714286],
       [ 8.21428571,  8.57142857,  8.92857143],
       [ 9.28571429,  9.64285714, 10.        ]])

In [59]:
arr=np.random.uniform(low=5,high=10,size=(5,3)) #optional/ we can assign them low and high

In [60]:
arr

array([[8.64454604, 9.24873489, 9.37245392],
       [7.01248485, 5.80837785, 7.238783  ],
       [8.57487574, 6.22744547, 5.73189697],
       [7.09509264, 9.85543975, 5.78051983],
       [5.65270838, 9.18241983, 5.31641603]])

Q. Print or show only 3 decimal places of the numpy array rand_arr.

In [61]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.29139124, 0.01475434, 0.12115976],
       [0.98359759, 0.22779036, 0.10921603],
       [0.05709684, 0.96099692, 0.98463446],
       [0.79590346, 0.91184407, 0.90657963],
       [0.28554154, 0.28812295, 0.20912141]])

In [62]:
np.set_printoptions(precision=3)

In [63]:
rand_arr

array([[0.291, 0.015, 0.121],
       [0.984, 0.228, 0.109],
       [0.057, 0.961, 0.985],
       [0.796, 0.912, 0.907],
       [0.286, 0.288, 0.209]])

In [64]:
np.arange(9).reshape(3,3).ndim

2

Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [65]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr


array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [66]:
# np.set_printoptions(precision=3)

In [67]:
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [68]:
np.set_printoptions(suppress=True, precision=6)

In [69]:
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements

In [71]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [78]:
np.set_printoptions(threshold=False)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

Q. Print the full numpy array a without truncating.

In [2]:
import numpy as np

In [5]:
arr=np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [80]:
import sys

In [81]:
np.set_printoptions(threshold=sys.maxsize)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
np.diff?

In [15]:
arr=np.random.randint(1,50,10)
arr

array([ 2, 19, 49, 26, 43,  9, 13,  7, 11, 22])

In [19]:
np.diff(arr)

array([ 17,  30, -23,  17, -34,   4,  -6,   4,  11])

In [18]:
np.diff(arr,n=2)

array([ 13, -53,  40, -51,  38, -10,  10,   7])

In [16]:
# arr=np.array([10,15,25,5])
newarr=np.diff(arr)
newarr

array([ 17,  30, -23,  17, -34,   4,  -6,   4,  11])

In [2]:
import numpy as np

In [4]:
x=np.ones((1,6))
for y in range(1,6,2):
    x[0][y]=0
x

array([[1., 0., 1., 0., 1., 0.]])

In [5]:
z=np.zeros((1,6))
z

array([[0., 0., 0., 0., 0., 0.]])

In [6]:
z==x

array([[False,  True, False,  True, False,  True]])

In [11]:
[i for i in range(0,2,2)] 

[0]

In [12]:
a=np.array([1,3,5])
b=np.array([2,4,5])
a==b

array([False, False,  True])

In [13]:
False+True+True

2

In [14]:
x=np.arange(1,7).reshape(3,2)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
np.split(x,[2])

[array([[1, 2],
        [3, 4]]),
 array([[5, 6]])]

In [16]:
a=np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(a)

[[1 2 3]
 [4 5 6]]


In [26]:
cc=np.resize(a,(3,2))

In [27]:
cc

array([[1, 0],
       [3, 4],
       [5, 6]])

In [28]:
cc[0,0]=55
cc

array([[55,  0],
       [ 3,  4],
       [ 5,  6]])

In [29]:
a

array([[1, 0, 3],
       [4, 5, 6]])

In [19]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b=np.reshape(a,(3,2))
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
b[0,0]=1
b

array([[1, 0],
       [3, 4],
       [5, 6]])

In [25]:
a

array([[1, 0, 3],
       [4, 5, 6]])

In [30]:
quiz=np.ones((2,2))
quiz

array([[1., 1.],
       [1., 1.]])

In [31]:
copy_quiz=np.ravel(quiz)
copy_quiz

array([1., 1., 1., 1.])

In [32]:
copy_quiz[0]=0
quiz

array([[0., 1.],
       [1., 1.]])

In [33]:
copy_quiz

array([0., 1., 1., 1.])

In [34]:
arr=np.arange(1,7).reshape(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
np.hsplit(arr,2)

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]])]

In [55]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
np.hsplit(arr,1)

[array([[1, 2],
        [3, 4],
        [5, 6]])]

In [39]:
np.hsplit(arr,[1,3])   #it is fancy indexing

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]]),
 array([], shape=(3, 0), dtype=int64)]

In [57]:
np.vsplit(arr,[2])

[array([[1, 2],
        [3, 4]]),
 array([[5, 6]])]

In [58]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
np.split(arr,[2])

[array([[1, 2],
        [3, 4]]),
 array([[5, 6]])]

In [43]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [46]:
np.hsplit(x,[3])

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]),
 array([[ 3.],
        [ 7.],
        [11.],
        [15.]])]

In [48]:
np.vsplit(x,2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [49]:
np.vsplit(x,[1])

[array([[0., 1., 2., 3.]]),
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [50]:
np.vsplit(x,[1,3])

[array([[0., 1., 2., 3.]]),
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]])]

In [61]:
x=np.arange(14)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [65]:
x.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [66]:
x.reshape(2,-1,order="F")

array([[ 0,  2,  4,  6,  8, 10, 12],
       [ 1,  3,  5,  7,  9, 11, 13]])

In [67]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.reshape(a,a.size,order="F")

array([1, 4, 2, 5, 3, 6])

In [78]:
np.reshape(a,a.size,order="C")

array([1, 2, 3, 4, 5, 6])

In [79]:
np.reshape(a,a.size)

array([1, 2, 3, 4, 5, 6])

In [80]:
np.reshape(a,a.size,order="A")

array([1, 2, 3, 4, 5, 6])

In [81]:
np.row_stack?

In [83]:
x=np.ones((2,2))
x

array([[1., 1.],
       [1., 1.]])

In [84]:
c=np.full((3,2),9)

In [85]:
c

array([[9, 9],
       [9, 9],
       [9, 9]])

In [87]:
np.vstack((x,c))

array([[1., 1.],
       [1., 1.],
       [9., 9.],
       [9., 9.],
       [9., 9.]])

In [88]:
x=np.array([5.4,6.7,8.8,7.],dtype="int32")
x

array([5, 6, 8, 7], dtype=int32)

In [89]:
y=x>5.3
y

array([False,  True,  True,  True])

In [90]:
y.any()

True

In [91]:
y.all()

False

## From numpy grand quiz

In [21]:
a=np.arange(7)

In [28]:
x=a.copy()
y=a.view()
print(x.base)
print(y.base)

None
[0 1 2 3 4 5 6]
